### ISSUE TITLE
[GitLab] `mattermost version` command broken

### ISSUE THREAD

**Issue by balasankarc** [mattermost/mattermost-server#10227]
#### Summary

Attempting to know the current version of mattermost by running `mattermost version` is not working. See logs below.

```bash
# From a random location in the file system
$ /opt/gitlab/embedded/bin/mattermost version
panic: Unable to find i18n directory

goroutine 1 [running]:
github.com/mattermost/mattermost-server/cmd/mattermost/commands.InitDBCommandContextCobra(0x20a3780, 0xc0000c9c80, 0x0, 0x0)
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/init.go:23 +0x30f
github.com/mattermost/mattermost-server/cmd/mattermost/commands.versionCmdF(0x20a3780, 0x20ef9d0, 0x0, 0x0, 0x0, 0x0)
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/version.go:25 +0x2b
github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).execute(0x20a3780, 0x20ef9d0, 0x0, 0x0, 0x20a3780, 0x20ef9d0)
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:762 +0x473
github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x209f760, 0x0, 0x200, 0xfd)
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).Execute(0x209f760, 0x407470, 0xc000084058)
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/mattermost/mattermost-server/cmd/mattermost/commands.Run(0xc0000a8010, 0x1, 0x1, 0xc0000c9f88, 0xc000084058)
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/root.go:14 +0x65
main.main()
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/cmd/mattermost/main.go:30 +0x62

# Moving to MM directory and retrying
$ cd /opt/gitlab/embedded/service/mattermost/

$ /opt/gitlab/embedded/bin/mattermost version
{"level":"info","msg":"Stopping Server..."}
{"level":"info","msg":"stopping websocket hub connections"}
{"level":"warn","msg":"We appear to have already sent the stop checking for deadlocks command"}
{"level":"info","msg":"Server stopped"}
panic: LoadConfig: Error opening config file=config.json, err=no config file found,
goroutine 1 [running]:
github.com/mattermost/mattermost-server/cmd/mattermost/commands.InitDBCommandContextCobra(0x20a3780, 0xc0001a5c80, 0x0, 0x0)
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/init.go:23 +0x30f
github.com/mattermost/mattermost-server/cmd/mattermost/commands.versionCmdF(0x20a3780, 0x20ef9d0, 0x0, 0x0, 0x0, 0x0)
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/version.go:25 +0x2b
github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).execute(0x20a3780, 0x20ef9d0, 0x0, 0x0, 0x20a3780, 0x20ef9d0)
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:762 +0x473
github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x209f760, 0x11ba560, 0xc0000a9a01, 0x20ef9d0)
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).Execute(0x209f760, 0x407470, 0xc000084058)
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/mattermost/mattermost-server/cmd/mattermost/commands.Run(0xc0000a8010, 0x1, 0x1, 0xc0001a5f88, 0xc000084058)
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/root.go:14 +0x65
main.main()
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/cmd/mattermost/main.go:30 +0x62

# Specifying config.json location
$ /opt/gitlab/embedded/bin/mattermost version --config /var/opt/gitlab/mattermost/config.json
{"level":"info","ts":1549358658.6623716,"caller":"utils/i18n.go:78","msg":"Loaded system translations for 'en' from '/opt/gitlab/embedded/service/mattermost/i18n/en.json'"}
{"level":"info","ts":1549358658.663088,"caller":"app/app.go:143","msg":"Server is initializing..."}
{"level":"info","ts":1549358658.6655104,"caller":"sqlstore/supplier.go:207","msg":"Pinging SQL master database"}
{"level":"error","ts":1549358658.6781023,"caller":"sqlstore/supplier.go:219","msg":"Failed to ping DB retrying in 10 seconds err=pq: Peer authentication failed for user \"gitlab_mattermost\""}
```

Not exactly sure why the last command failed, and why checking `version` of the binary needs to connect to the database. Confirmed that the config.json file contains correct values for SQL connection (GitLab packages use env variables to set this primarily, which gets reciprocated to the config.json file by Mattermost).

@hmhealey

**Comment by hmhealey** [comment]
The reason that command needs the database connection is because it gets the schema version from the database. The reason you're seeing that error is because GitLab Omnibus configures the database to allow access to Mattermost based on the user that Mattermost runs as rather than using a username/password, so you need a `sudo -u mattermost` before your command like
```bash
sudo -u mattermost /opt/gitlab/embedded/bin/mattermost --config /var/opt/gitlab/mattermost/config.json version
```

**Comment by balasankarc** [comment]
> The reason that command needs the database connection is because it gets the schema version from the database.

Ah! Ok.

> GitLab Omnibus configures the database to allow access to Mattermost based on the user that Mattermost runs

This I kinda guessed was the reason for the error, but wasn't sure why DB access was a must.

Thanks for the clarification.
