### ISSUE TITLE
Write an automated test using `cypress` for "Long post with multiple attachments"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10370]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14322)

*Test Key: M14322*

1. Add 4 attachments to a post
2. Copy and paste the text below into the message box and post 
{code:java}
The quick, brown fox jumps over a lazy dog. DJs flock by when MTV ax quiz prog. Junk MTV quiz graced by fox whelps. Bawds jog, flick quartz, vex nymphs. Waltz, bad nymph, for quick jigs vex! Fox nymphs grab quick-jived waltz. Brick quiz whangs jumpy veldt fox. Bright vixens jump; dozy fowl quack. Quick wafting zephyrs vex bold Jim. Quick zephyrs blow, vexing daft Jim. Sex-charged fop blew my junk TV quiz. How quickly daft jumping zebras vex. Two driven jocks help fax my big quiz. Quick, Baz, get my woven flax jodhpurs! "Now fax quiz Jack!" my brave ghost pled. Five quacking zephyrs jolt my wax bed. Flummoxed by job, kvetching W. zaps Iraq. Cozy sphinx waves quart jug of bad milk. A very bad quack might jinx zippy fowls. Few quips galvanized the mock jury box. Quick brown dogs jump over the lazy fox. The jay, pig, fox, zebra, and my wolves quack! Blowzy red vixens fight for a quick jump. Joaquin Phoenix was gazed by MTV for luck. A wizard’s job is to vex chumps quickly in fog. Watch "Jeopardy!", Alex Trebek's fun TV quiz game. Woven silk pyjamas exchanged for blue quartz. Brawny gods just flocked up to quiz and vex him. Adjusting quiver and bow, Zompyc[1] killed the fox. My faxed joke won a pager in the cable TV quiz show. Amazingly few discotheques provide jukeboxes. My girl wove six dozen plaid jackets before she quit. Six big devils from Japan quickly forgot how to waltz. Big July earthquakes confound zany experimental vow. Foxy parsons quiz and cajole the lovably dim wiki-girl. Have a pick: twenty six letters - no forcing a jumbled quiz! Crazy Fredericka bought many very exquisite opal jewels. Sixty zippers were quickly picked from the woven jute bag. A quick movement of the enemy will jeopardize six gunboats. All questions asked by five watch experts amazed the judge. Jack quietly moved up front and seized the big ball of wax. The quick, brown fox jumps over a lazy dog. DJs flock by when MTV ax quiz prog. Junk MTV quiz graced by fox whelps. Bawds jog, flick quartz, vex nymphs. Waltz, bad nymph, for quick jigs vex! Fox nymphs grab quick-jived waltz. Brick quiz whangs jumpy veldt fox. Bright vixens jump; dozy fowl quack. Quick wafting zephyrs vex bold Jim. Quick zephyrs blow, vexing daft Jim. Sex-charged fop blew my junk TV quiz. How quickly daft jumping zebras vex. Two driven jocks help fax my big quiz. Quick, Baz, get my woven flax jodhpurs! "Now fax quiz Jack!" my brave ghost pled. Five quacking zephyrs jolt my wax bed. Flummoxed by job, kvetching W. zaps Iraq. Cozy sphinx waves quart jug of bad milk. A very bad quack might jinx zippy fowls. Few quips galvanized the mock jury box. Quick brown dogs jump over the lazy fox. The jay, pig, fox, zebra, and my wolves quack! Blowzy red vixens fight for a quick jump. Joaquin Phoenix was gazed by MTV for luck. A wizard’s job is to vex chumps quickly in fog. Watch "Jeopardy!", Alex Trebek's fun TV quiz game. Woven silk pyjamas exchanged for blue quartz. Brawny gods just flocked up to quiz and vex him. Adjusting quiver and bow, Zompyc[1] killed the fox. My faxed joke won a pager in the cable TV quiz show. Amazingly few discotheques provide jukeboxes. My girl wove six dozen plaid jackets before she quit. Six big devils from Japan quickly forgot how to waltz. Big July earthquakes confound zany experimental vow. Foxy parsons quiz and cajole the lovably dim wiki-girl. Have a pick: twenty six letters - no forcing a jumbled quiz! Crazy Fredericka bought many very exquisite opal jewels. Sixty zippers were quickly picked from the woven jute bag. A quick movement of the enemy will jeopardize six gunboats. All questions asked by five watch experts amazed the judge. Jack quietly moved up front and seized the big ball of wax. The quick, brown fox jumps over a lazy dog. DJs flock by when MTV ax quiz prog. Junk MTV quiz graced by fox whelps. Bawds jog, flick quartz, vex nymphs. Waltz, bad nymph, for quick jigs vex! Fox nymphs grab quick-jived waltz. Brick quiz whangs jumpy veldt fox. Hello this is a long post, with more than 4000 characters, plus multiple attachments.
{code}

Expected:
- Attachment previews/thumbnails display as expected, when viewing full or partial post
- Can click one of the attachments and cycle through the multiple attachment previews as usual

See our end-to-end testing documentation for reference - https://developers.mattermost.com/contribute/webapp/end-to-end-tests/

**Comment by nadaa** [comment]
Hi, can I work on this?
Thanks!

**Comment by hanzei** [comment]
Surely @nadaa! Thanks for working on this. Let me know, if you have questions.

**Comment by nadaa** [comment]
Hi @hanzei, I have an issue while setting up the developer machine. I am using Windows and I need some help, is there any place to post issues about installation?. Thanks!

**Comment by nadaa** [comment]
Do I need to update the mattermost-server/client or the mattermost-webapp?

**Comment by hanzei** [comment]
This need to be implemented in the webapp.

**Comment by nadaa** [comment]
Hi @hanzei 
I did this:
run the server ``` make run```
run e2e test ```npm run cypress:open```
cypress window opens but when I click on any test. cypress closes.
I got this on the screen while running cypress "Cypress:5357): GLib-GIO-CRITICAL **: 19:26:24.859: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
"
What do you suggest?

**Comment by hanzei** [comment]
@saturninoabril Could you please help with the above question?

**Comment by saturninoabril** [comment]
I haven't seen that error.  What dev OS are you using? If Ubuntu, this thread - https://github.com/cypress-io/cypress/issues/1526 - might help you.

**Comment by nadaa** [comment]
@saturninoabril, yes Ubuntu. I will check that. Thank you!

**Comment by nadaa** [comment]
This is the whole error:
Cypress:28172): GLib-GIO-CRITICAL **: 19:16:02.319: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
GET /__/ 200 627.796 ms - -
GET /__cypress/runner/cypress_runner.css 200 1164.918 ms - -
GET /__cypress/runner/cypress_runner.js 200 7947.635 ms - -
GET /__cypress/runner/fonts/fontawesome-webfont.woff2?v=4.7.0 200 60.816 ms - 77160
GET /__cypress/iframes/integration/post_header/post_header_spec.js 200 386.413 ms - 759
{ Error: watch /home/nada/go/src/github.com/mattermost/mattermost-webapp/package.json ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at createFsWatchInstance (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at /home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)

  code: 'ENOSPC',
  errno: 'ENOSPC',
  syscall: 'watch /home/nada/go/src/github.com/mattermost/mattermost-webapp/package.json',
  filename: '/home/nada/go/src/github.com/mattermost/mattermost-webapp/package.json' }
Error: watch /home/nada/go/src/github.com/mattermost/mattermost-webapp/package.json ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at createFsWatchInstance (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at /home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)

{ Error: watch /home/nada/go/src/github.com/mattermost/mattermost-webapp/package.json ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at createFsWatchInstance (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at /home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)

  code: 'ENOSPC',
  errno: 'ENOSPC',
  syscall: 'watch /home/nada/go/src/github.com/mattermost/mattermost-webapp/package.json',
  filename: '/home/nada/go/src/github.com/mattermost/mattermost-webapp/package.json' }
Error: watch /home/nada/go/src/github.com/mattermost/mattermost-webapp/package.json ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at createFsWatchInstance (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at /home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)

GET /__cypress/tests?p=cypress/integration/post_header/post_header_spec.js-882 - - ms - -
GET /__cypress/tests?p=cypress/support/index.js-477 - - ms - -
{ Error: watch /home/nada/go/src/github.com/mattermost/mattermost-webapp/cypress/support/index.js ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at createFsWatchInstance (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at /home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)

  code: 'ENOSPC',
  errno: 'ENOSPC',
  syscall: 'watch /home/nada/go/src/github.com/mattermost/mattermost-webapp/cypress/support/index.js',
  filename: '/home/nada/go/src/github.com/mattermost/mattermost-webapp/cypress/support/index.js' }
Error: watch /home/nada/go/src/github.com/mattermost/mattermost-webapp/cypress/support/index.js ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at createFsWatchInstance (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at /home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)

{ Error: watch /home/nada/go/src/github.com/mattermost/mattermost-webapp/cypress/integration/post_header/post_header_spec.js ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at createFsWatchInstance (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at /home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)

  code: 'ENOSPC',
  errno: 'ENOSPC',
  syscall: 'watch /home/nada/go/src/github.com/mattermost/mattermost-webapp/cypress/integration/post_header/post_header_spec.js',
  filename: '/home/nada/go/src/github.com/mattermost/mattermost-webapp/cypress/integration/post_header/post_header_spec.js' }
Error: watch /home/nada/go/src/github.com/mattermost/mattermost-webapp/cypress/integration/post_header/post_header_spec.js ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at createFsWatchInstance (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at /home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)

{ Error: watch /home/nada/go/src/github.com/mattermost/mattermost-webapp/cypress/support/commands.js ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at createFsWatchInstance (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at /home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)

  code: 'ENOSPC',
  errno: 'ENOSPC',
  syscall: 'watch /home/nada/go/src/github.com/mattermost/mattermost-webapp/cypress/support/commands.js',
  filename: '/home/nada/go/src/github.com/mattermost/mattermost-webapp/cypress/support/commands.js' }
Error: watch /home/nada/go/src/github.com/mattermost/mattermost-webapp/cypress/support/commands.js ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at createFsWatchInstance (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at /home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)

{ Error: watch /home/nada/go/src/github.com/mattermost/mattermost-webapp/cypress/support/validators.js ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at createFsWatchInstance (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at /home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)

  code: 'ENOSPC',
  errno: 'ENOSPC',
  syscall: 'watch /home/nada/go/src/github.com/mattermost/mattermost-webapp/cypress/support/validators.js',
  filename: '/home/nada/go/src/github.com/mattermost/mattermost-webapp/cypress/support/validators.js' }
Error: watch /home/nada/go/src/github.com/mattermost/mattermost-webapp/cypress/support/validators.js ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at createFsWatchInstance (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at /home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)

{ Error: watch /home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/@babel/runtime/helpers/interopRequireDefault.js ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at createFsWatchInstance (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at /home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)

  code: 'ENOSPC',
  errno: 'ENOSPC',
  syscall: 'watch /home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/@babel/runtime/helpers/interopRequireDefault.js',
  filename: '/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/@babel/runtime/helpers/interopRequireDefault.js' }
Error: watch /home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/@babel/runtime/helpers/interopRequireDefault.js ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at createFsWatchInstance (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at /home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)

{ Error: watch /home/nada/go/src/github.com/mattermost/mattermost-webapp/cypress/fixtures/users.json ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at createFsWatchInstance (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at /home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)

  code: 'ENOSPC',
  errno: 'ENOSPC',
  syscall: 'watch /home/nada/go/src/github.com/mattermost/mattermost-webapp/cypress/fixtures/users.json',
  filename: '/home/nada/go/src/github.com/mattermost/mattermost-webapp/cypress/fixtures/users.json' }
Error: watch /home/nada/go/src/github.com/mattermost/mattermost-webapp/cypress/fixtures/users.json ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at createFsWatchInstance (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at /home/nada/.cache/Cypress/3.1.5/Cypress/resources/app/packages/server/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)

**Comment by nadaa** [comment]
I found the solution here: https://stackoverflow.com/questions/22475849/node-js-what-is-enospc-error-and-how-to-solve
Thank you :)

**Comment by saturninoabril** [comment]
Glad you solved it!

Would you like to contribute to our developer docs, documenting the [E2E troubleshooting](https://github.com/mattermost/mattermost-developer-documentation/blob/master/site/content/contribute/webapp/end-to-end-tests.md#troubleshooting) with your encountered error and solution?

**Comment by nadaa** [comment]
@saturninoabril, Sure!

**Comment by RajatVaryani** [comment]
@hanzei Can I own this up?

**Comment by saturninoabril** [comment]
Sure and thanks @RajatVaryani!

**Comment by RajatVaryani** [comment]
@hanzei I won't be able to work on this. I have couple of other PRs as well. Want to concentrate on it first.

**Comment by saturninoabril** [comment]
No worries @RajatVaryani and thanks for looking into this.

**Comment by Abebw** [comment]
I'd be happy to take this up.

**Comment by jasonblais** [comment]
Thanks @Abebw! How are things going, any questions so far? :)

**Comment by Abebw** [comment]
@jasonblais unfortunately I won't be finishing this task. Feel free to unassign me and readd up for grams.

**Comment by VishalSwarnkar** [comment]
I'll take this one

**Comment by VishalSwarnkar** [comment]
Hi @jasonblais, raised pull request for review. Thanks
