### ISSUE TITLE
System raised an error when updating configuration through API v4

### ISSUE THREAD

**Issue by Sharuru** [mattermost/mattermost-server#10531]
#### Summary
System raised an error when updating configuration through API v4

#### Steps to reproduce
0. Environment
```BASH
~ $ mattermost version
Version: 5.9.0
Build Number: 5.9.0
Build Date: Fri Mar 15 22:02:44 UTC 2019
Build Hash: 5ef499caae2bb751438b19151a9fcb4b27830bca
Build Enterprise Ready: true
DB Version: 5.9.0
```
1. Generate a personal token with administration rights for an administrator.
2. Request `http://link.to.mattermost/api/v4/config` with PUT method by Postman
(refs: https://api.mattermost.com/#tag/system%2Fpaths%2F~1config%2Fput)

#### Expected behavior
1. System configuration should be updated successfully.

#### Observed behavior (that appears unintentional) 
1. `mattermost.log` shows error:
```JSON
{"level":"error","ts":1553840392.0891113,"caller":"app/server.go:376","msg":"Please check the std error output for the stack trace"}
{"level":"error","ts":1553840392.0891836,"caller":"app/server.go:377","msg":"runtime error: invalid memory address or nil pointer dereference"}
```
2. Mattermost server shows error:
```LOG
goroutine 3264455 [running]:
runtime/debug.Stack(0xc0052f88b0, 0xf060a4, 0xc007769880)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.recoveryHandler.log(0x19b21c0, 0xc0024c9f10, 0x19b1e00, 0x27a3770, 0x1, 0xc006993a30, 0x1, 0x1)
	/go/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers/recovery.go:89 +0x71
github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1(0x19be760, 0xc00669c000, 0x19b21c0, 0xc0024c9f10, 0x19b1e00, 0x27a3770, 0x1)
	/go/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers/recovery.go:74 +0xda
panic(0x14b35a0, 0x2743ba0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/mattermost/mattermost-server/api4.updateConfig(0xc0055573e0, 0x19be760, 0xc00669c000, 0xc003fe1100)
	/go/src/github.com/mattermost/mattermost-server/api4/system.go:142 +0x146
github.com/mattermost/mattermost-server/web.Handler.ServeHTTP(0xc001e404f0, 0x174e8d0, 0x10001, 0x0, 0x0, 0x19be760, 0xc00669c000, 0xc003fe1100)
	/go/src/github.com/mattermost/mattermost-server/web/handlers.go:151 +0x14fa
github.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0024c9f10, 0x19be760, 0xc00669c000, 0xc003fe1100)
	/go/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux/mux.go:162 +0xf1
github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP(0x19b21c0, 0xc0024c9f10, 0x19b1e00, 0x27a3770, 0x1, 0x19be760, 0xc00669c000, 0xc003fe0f00)
	/go/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers/recovery.go:78 +0xb0
net/http.serverHandler.ServeHTTP(0xc00140c1a0, 0x19be760, 0xc00669c000, 0xc003fe0f00)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc00736a6e0, 0x19bfa20, 0xc008de44c0)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5
```
3. No error log found for the database.
4. Update system configuration through GUI, CLI are both succeeded.
5. Have tried some other request like `/api/v4/me` or using the invalid token are both responded as expected.

**Comment by Sharuru** [comment]
Update:
Have found that the proper use of this API is to send the **ALL** configuration, not just the key I want to change. Maybe `POST` method is better instead of `PUT` for restful design...
