### ISSUE TITLE
Failed to call GetTeam of plugin API

### ISSUE THREAD

**Issue by kaakaa** [mattermost/mattermost-server#10548]
#### Summary
Failed to call GetTeam of plugin API.
>  RPC call to GetTeam API failed: reading body gob: type mismatch in decoder: want struct type sql.NullBool; got non-struct 

#### Steps to reproduce
1. Upload and enable [Matterpoll plugin](https://github.com/matterpoll/matterpoll) (deploy master branch, not 1.0.3 release)
2. Create a poll
3. Click [End Poll] button

#### Expected behavior
* Poll ends successfully

#### Observed behavior (that appears unintentional) 
* Poll doesn't end and no error message is displayed
* I can see error logs for this in system console

```
2019-04-03T15:04:47.198+0900    debug   mlog/sugar.go:15        New request:    {"plugin_id": "com.github.matterpoll.matterpoll", "Host": "localhost:8065", "RequestURI": "/plugins/com.github.matterpoll.matterpoll/api/v1/polls/jo43a6n14pnijg8ekahd6pmfth/end", "Method": "POST"}
2019-04-03T15:04:47.333+0900    info    io/io.go:364    2019/04/03 15:04:47 RPC call to GetTeam API failed: reading body gob: type mismatch in decoder: want struct type sql.NullBool; got non-struct   {"plugin_id": "com.github.matterpoll.matterpoll", "source": "plugin_stderr"}
2019-04-03T15:04:47.336+0900    debug   plugin/hclog_adapter.go:34      panic: runtime error: invalid memory address or nil pointer dereference {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.336+0900    debug   plugin/hclog_adapter.go:34      [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15b35b8] {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.336+0900    debug   plugin/hclog_adapter.go:34              {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.336+0900    debug   plugin/hclog_adapter.go:34      goroutine 67 [running]: {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.336+0900    debug   plugin/hclog_adapter.go:34      github.com/matterpoll/matterpoll/server/plugin.(*MatterpollPlugin).postEndPollAnnouncement(0xc0000809c0, 0xc0002b4200, 0xc0000a4130, 0x4)       {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.336+0900    debug   plugin/hclog_adapter.go:34              /Users/y-nemoto/go/src/github.com/matterpoll/matterpoll/server/plugin/api.go:366 +0x268 {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.336+0900    debug   plugin/hclog_adapter.go:34      github.com/matterpoll/matterpoll/server/plugin.(*MatterpollPlugin).handleEndPoll(0xc0000809c0, 0x182ab00, 0xc000402880, 0xc00028e300)   {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.336+0900    debug   plugin/hclog_adapter.go:34              /Users/y-nemoto/go/src/github.com/matterpoll/matterpoll/server/plugin/api.go:353 +0x549 {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.336+0900    debug   plugin/hclog_adapter.go:34      github.com/matterpoll/matterpoll/server/plugin.(*MatterpollPlugin).handleEndPoll-fm(0x182ab00, 0xc000402880, 0xc00028e300)      {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.336+0900    debug   plugin/hclog_adapter.go:34              /Users/y-nemoto/go/src/github.com/matterpoll/matterpoll/server/plugin/api.go:87 +0x48   {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.336+0900    debug   plugin/hclog_adapter.go:34      net/http.HandlerFunc.ServeHTTP(0xc00001fba0, 0x182ab00, 0xc000402880, 0xc00028e300)     {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.336+0900    debug   plugin/hclog_adapter.go:34              /usr/local/Cellar/go/1.11.1/libexec/src/net/http/server.go:1964 +0x44   {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.336+0900    debug   plugin/hclog_adapter.go:34      github.com/matterpoll/matterpoll/server/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0002c6930, 0x182ab00, 0xc000402880, 0xc00028e300)  {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.336+0900    debug   plugin/hclog_adapter.go:34              /Users/y-nemoto/go/src/github.com/matterpoll/matterpoll/server/vendor/github.com/gorilla/mux/mux.go:162 +0xf1   {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.336+0900    debug   plugin/hclog_adapter.go:34      github.com/matterpoll/matterpoll/server/plugin.(*MatterpollPlugin).ServeHTTP(0xc0000809c0, 0xc0002d47d0, 0x182ab00, 0xc000402880, 0xc000400900) {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.336+0900    debug   plugin/hclog_adapter.go:34              /Users/y-nemoto/go/src/github.com/matterpoll/matterpoll/server/plugin/api.go:94 +0x1cd  {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.336+0900    debug   plugin/hclog_adapter.go:34      github.com/matterpoll/matterpoll/server/vendor/github.com/mattermost/mattermost-server/plugin.(*hooksRPCServer).ServeHTTP(0xc0002824e0, 0xc0003d3840, 0x1d48880, 0x0, 0x0)      {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.336+0900    debug   plugin/hclog_adapter.go:34              /Users/y-nemoto/go/src/github.com/matterpoll/matterpoll/server/vendor/github.com/mattermost/mattermost-server/plugin/client_rpc.go:356 +0x254   {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.336+0900    debug   plugin/hclog_adapter.go:34      reflect.Value.call(0xc00013e6c0, 0xc000146190, 0x13, 0x174bcb0, 0x4, 0xc000055f18, 0x3, 0x3, 0xc00030c000, 0x0, ...)    {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.337+0900    debug   plugin/hclog_adapter.go:34              /usr/local/Cellar/go/1.11.1/libexec/src/reflect/value.go:447 +0x449     {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.337+0900    debug   plugin/hclog_adapter.go:34      reflect.Value.Call(0xc00013e6c0, 0xc000146190, 0x13, 0xc000480f18, 0x3, 0x3, 0x0, 0x0, 0x0)     {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.337+0900    debug   plugin/hclog_adapter.go:34              /usr/local/Cellar/go/1.11.1/libexec/src/reflect/value.go:308 +0xa4      {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.337+0900    debug   plugin/hclog_adapter.go:34      net/rpc.(*service).call(0xc00014c180, 0xc0002d40a0, 0xc0001501b0, 0xc0001501c0, 0xc00025a600, 0xc000142920, 0x160cdc0, 0xc0003d3840, 0x16, 0x161c380, ...)      {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.337+0900    debug   plugin/hclog_adapter.go:34              /usr/local/Cellar/go/1.11.1/libexec/src/net/rpc/server.go:384 +0x14e    {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.337+0900    debug   plugin/hclog_adapter.go:34      created by net/rpc.(*Server).ServeCodec {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.337+0900    debug   plugin/hclog_adapter.go:34              /usr/local/Cellar/go/1.11.1/libexec/src/net/rpc/server.go:481 +0x47e    {"plugin_id": "com.github.matterpoll.matterpoll"}
2019-04-03T15:04:47.338+0900    error   mlog/log.go:172 Plugin failed to ServeHTTP, RPC call failed     {"plugin_id": "com.github.matterpoll.matterpoll", "error": "unexpected EOF"}
2019-04-03T15:04:47.338+0900    debug   plugin/hclog_adapter.go:32      plugin process exited   {"plugin_id": "com.github.matterpoll.matterpoll", "wrapped_extras": "pathplugins/com.github.matterpoll.matterpoll/server/dist/plugin-darwin-amd64pid3493errorexit status 2"}
2019-04-03T15:04:47.339+0900    error   mlog/log.go:172 Action integration error        {"path": "/api/v4/posts/n4fuwbhhgfr68bgftfigfo3t3h/actions/wm7iagab67ye5mfn86sogr1w4a", "request_id": "nz8negbjf78kidwogrkbs31w3w", "ip_addr": "::1", "user_id": "7g37ywimh3bwfqsks1x91qxttc", "method": "POST", "err_where": "DoActionRequest", "http_code": 400, "err_details": "status=500"}
```

#### Possible fixes
I supposed that this issue is caused by #10526, and it would be needed to migrate existing `team` data.

**Comment by hanzei** [comment]
Hey @kaakaa,

Thanks for the report. Just to confirm: Running v1.0.3 of Matterpoll works fine with `mater` Server?

Would you mind updating the dependencies of Matterpoll to the latest `master' and test again?

**Comment by kaakaa** [comment]
Ah...you are right. After updating dependencies of Matterpoll, poll works fine.
Thanks @hanzei !

**Comment by hanzei** [comment]
Glad it works.

> Just to confirm: Running v1.0.3 of Matterpoll works fine with `mater` Server?

Can you confirm this?

**Comment by kaakaa** [comment]
Yes, Matterpoll v1.0.3 works fine, so we don't need to release another version of Matterpoll including bug fix.

**Comment by hanzei** [comment]
Thanks for confirming!
