### ISSUE TITLE
runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by vincentbab** [mattermost/mattermost-server#10751]
#### Summary
runtime error: slice bounds out of range

#### Steps to reproduce
Write "://///" in a direct message

#### Expected behavior
Writing this message will lead to an error when retreiving posts of the channel
The error seems to be in markdown.parseURLAutolink
Here is the stack trace:
`Apr 29 10:56:06 localhost mattermost[4783]: {"level":"error","ts":1556535366.6278725,"caller":"app/server.go:376","msg":"Please check the std error output for the stack trace"}
Apr 29 10:56:06 localhost mattermost[4783]: {"level":"error","ts":1556535366.6279519,"caller":"app/server.go:377","msg":"runtime error: slice bounds out of range"}
Apr 29 10:56:06 localhost mattermost[4783]: goroutine 4782 [running]:
Apr 29 10:56:06 localhost mattermost[4783]: runtime/debug.Stack(0xc002a51440, 0xf060a4, 0xc0033499b0)
Apr 29 10:56:06 localhost mattermost[4783]: #011/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
Apr 29 10:56:06 localhost mattermost[4783]: runtime/debug.PrintStack()
Apr 29 10:56:06 localhost mattermost[4783]: #011/usr/local/go/src/runtime/debug/stack.go:16 +0x22
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.recoveryHandler.log(0x19b21c0, 0xc0025ff340, 0x19b1e00, 0x27a3770, 0x1, 0xc0029fed60, 0x1, 0x1)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers/recovery.go:89 +0x71
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1(0x19be760, 0xc0024101c0, 0x19b21c0, 0xc0025ff340, 0x19b1e00, 0x27a3770, 0x1)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers/recovery.go:74 +0xda
Apr 29 10:56:06 localhost mattermost[4783]: panic(0x14b35a0, 0x2743bf0)
Apr 29 10:56:06 localhost mattermost[4783]: #011/usr/local/go/src/runtime/panic.go:513 +0x1b9
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/utils/markdown.parseURLAutolink(0xc001798068, 0x6, 0x0, 0x0, 0x0, 0x0)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/utils/markdown/autolink.go:82 +0x285
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/utils/markdown.(*inlineParser).parseAutolink(0xc0019e5080, 0x3a, 0x3a)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/utils/markdown/inlines.go:504 +0x404
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/utils/markdown.(*inlineParser).Parse(0xc0019e5080, 0xc0019e5080, 0x1, 0x1)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/utils/markdown/inlines.go:580 +0x1af
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/utils/markdown.ParseInlines(0xc001798068, 0x6, 0xc002910230, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc002a51830, 0xc002a519b0, ...)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/utils/markdown/inlines.go:594 +0xe8
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/utils/markdown.(*Paragraph).ParseInlines(0xc001de2e80, 0x0, 0x0, 0x0, 0x0, 0x7f45ecc0ce60, 0x0)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/utils/markdown/paragraph.go:19 +0x77
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/utils/markdown.Inspect.func1(0x19c18e0, 0xc001de2e80, 0xc002a12f20)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/utils/markdown/inspect.go:16 +0xd0
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/utils/markdown.InspectBlock(0x19c18e0, 0xc001de2e80, 0xc002a51950)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/utils/markdown/inspect.go:29 +0x3e
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/utils/markdown.InspectBlock(0x19c17a0, 0xc002a12ec0, 0xc002a51950)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/utils/markdown/inspect.go:35 +0x16f
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/utils/markdown.Inspect(0xc001798068, 0x6, 0xc002a519c8)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/utils/markdown/inspect.go:10 +0xa7
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/app.getFirstLinkAndImages(0xc001798068, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/app/post_metadata.go:278 +0x9b
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/app.(*App).PreparePostForClient(0xc003d93dc0, 0xc0046739e0, 0xc001661a00, 0x1a)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/app/post_metadata.go:82 +0x25c
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/app.(*App).PreparePostListForClient(0xc003d93dc0, 0xc00197d1c0, 0x4)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/app/post_metadata.go:46 +0x15e
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/api4.getPostsForChannel(0xc0021a51a0, 0x19be760, 0xc0024101c0, 0xc001c10e00)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/api4/post.go:170 +0x339
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/web.Handler.ServeHTTP(0xc0023b7c40, 0x174e508, 0x10001, 0x0, 0x0, 0x19be760, 0xc0024101c0, 0xc001c10e00)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/web/handlers.go:151 +0x14fa
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0025ff340, 0x19be760, 0xc0024101c0, 0xc001c10e00)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux/mux.go:162 +0xf1
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP(0x19b21c0, 0xc0025ff340, 0x19b1e00, 0x27a3770, 0x1, 0x19be760, 0xc0024101c0, 0xc001c10c00)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers/recovery.go:78 +0xb0
Apr 29 10:56:06 localhost mattermost[4783]: net/http.serverHandler.ServeHTTP(0xc001fb2a90, 0x19be760, 0xc0024101c0, 0xc001c10c00)
Apr 29 10:56:06 localhost mattermost[4783]: #011/usr/local/go/src/net/http/server.go:2741 +0xab
Apr 29 10:56:06 localhost mattermost[4783]: net/http.(*conn).serve(0xc00020e3c0, 0x19bfa20, 0xc0025e8000)
Apr 29 10:56:06 localhost mattermost[4783]: #011/usr/local/go/src/net/http/server.go:1847 +0x646
Apr 29 10:56:06 localhost mattermost[4783]: created by net/http.(*Server).Serve
Apr 29 10:56:06 localhost mattermost[4783]: #011/usr/local/go/src/net/http/server.go:2851 +0x2f5
Apr 29 10:56:06 localhost mattermost[4783]: {"level":"error","ts":1556535366.6379142,"caller":"app/server.go:376","msg":"Please check the std error output for the stack trace"}
Apr 29 10:56:06 localhost mattermost[4783]: {"level":"error","ts":1556535366.637954,"caller":"app/server.go:377","msg":"runtime error: slice bounds out of range"}
Apr 29 10:56:06 localhost mattermost[4783]: goroutine 4539 [running]:
Apr 29 10:56:06 localhost mattermost[4783]: runtime/debug.Stack(0xc0024f7440, 0xf060a4, 0xc003349a40)
Apr 29 10:56:06 localhost mattermost[4783]: #011/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
Apr 29 10:56:06 localhost mattermost[4783]: runtime/debug.PrintStack()
Apr 29 10:56:06 localhost mattermost[4783]: #011/usr/local/go/src/runtime/debug/stack.go:16 +0x22
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.recoveryHandler.log(0x19b21c0, 0xc0025ff340, 0x19b1e00, 0x27a3770, 0x1, 0xc0029ff550, 0x1, 0x1)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers/recovery.go:89 +0x71
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1(0x19be760, 0xc001172700, 0x19b21c0, 0xc0025ff340, 0x19b1e00, 0x27a3770, 0x1)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers/recovery.go:74 +0xda
Apr 29 10:56:06 localhost mattermost[4783]: panic(0x14b35a0, 0x2743bf0)
Apr 29 10:56:06 localhost mattermost[4783]: #011/usr/local/go/src/runtime/panic.go:513 +0x1b9
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/utils/markdown.parseURLAutolink(0xc002a2ddc8, 0x6, 0x0, 0x0, 0x0, 0x0)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/utils/markdown/autolink.go:82 +0x285
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/utils/markdown.(*inlineParser).parseAutolink(0xc0019e5580, 0x3a, 0x3a)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/utils/markdown/inlines.go:504 +0x404
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/utils/markdown.(*inlineParser).Parse(0xc0019e5580, 0xc0019e5580, 0x1, 0x1)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/utils/markdown/inlines.go:580 +0x1af
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/utils/markdown.ParseInlines(0xc002a2ddc8, 0x6, 0xc002910380, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc0024f7830, 0xc0024f79b0, ...)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/utils/markdown/inlines.go:594 +0xe8
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/utils/markdown.(*Paragraph).ParseInlines(0xc001e37c80, 0x0, 0x0, 0x0, 0x0, 0x7f45ecc0ce60, 0x0)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/utils/markdown/paragraph.go:19 +0x77
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/utils/markdown.Inspect.func1(0x19c18e0, 0xc001e37c80, 0xc002a13320)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/utils/markdown/inspect.go:16 +0xd0
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/utils/markdown.InspectBlock(0x19c18e0, 0xc001e37c80, 0xc0024f7950)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/utils/markdown/inspect.go:29 +0x3e
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/utils/markdown.InspectBlock(0x19c17a0, 0xc002a13300, 0xc0024f7950)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/utils/markdown/inspect.go:35 +0x16f
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/utils/markdown.Inspect(0xc002a2ddc8, 0x6, 0xc0024f79c8)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/utils/markdown/inspect.go:10 +0xa7
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/app.getFirstLinkAndImages(0xc002a2ddc8, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/app/post_metadata.go:278 +0x9b
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/app.(*App).PreparePostForClient(0xc001ea41c0, 0xc0040bbb00, 0xc0024b0c00, 0x1a)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/app/post_metadata.go:82 +0x25c
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/app.(*App).PreparePostListForClient(0xc001ea41c0, 0xc001094f40, 0x4)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/app/post_metadata.go:46 +0x15e
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/api4.getPostsForChannel(0xc0023ec0f0, 0x19be760, 0xc001172700, 0xc001817600)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/api4/post.go:170 +0x339
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/web.Handler.ServeHTTP(0xc0023b7c40, 0x174e508, 0x10001, 0x0, 0x0, 0x19be760, 0xc001172700, 0xc001817600)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/web/handlers.go:151 +0x14fa
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0025ff340, 0x19be760, 0xc001172700, 0xc001817600)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux/mux.go:162 +0xf1
Apr 29 10:56:06 localhost mattermost[4783]: github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP(0x19b21c0, 0xc0025ff340, 0x19b1e00, 0x27a3770, 0x1, 0x19be760, 0xc001172700, 0xc001817400)
Apr 29 10:56:06 localhost mattermost[4783]: #011/go/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers/recovery.go:78 +0xb0
Apr 29 10:56:06 localhost mattermost[4783]: net/http.serverHandler.ServeHTTP(0xc001fb2a90, 0x19be760, 0xc001172700, 0xc001817400)
Apr 29 10:56:06 localhost mattermost[4783]: #011/usr/local/go/src/net/http/server.go:2741 +0xab
Apr 29 10:56:06 localhost mattermost[4783]: net/http.(*conn).serve(0xc0042d0b40, 0x19bfa20, 0xc004303a00)
Apr 29 10:56:06 localhost mattermost[4783]: #011/usr/local/go/src/net/http/server.go:1847 +0x646
Apr 29 10:56:06 localhost mattermost[4783]: created by net/http.(*Server).Serve
Apr 29 10:56:06 localhost mattermost[4783]: #011/usr/local/go/src/net/http/server.go:2851 +0x2f5`

**Comment by hanzei** [comment]
Thanks for the report @vincentbab. I was able to reproduce the issue.

Please note that this does **not** crash the server. This bug also has no implications for the end user.

@vincentbab Are you interested in working on fix for this bug?

**Comment by amyblais** [comment]
Ticket: https://mattermost.atlassian.net/browse/MM-15328.

**Comment by vincentbab** [comment]
Unfortunately I have no experience in Golang so I won't be able to fix this issue myself.

The server does not crash indeed but there is an implication for the end user. You cannot get the history of the channel and if this message is in the last 30 messages the channel seems "broken". This behavior only happen if you refresh the page.

**Comment by hanzei** [comment]
Thank you for the detailed response @vincentbab  :+1:

**Comment by amyblais** [comment]
Hi @vincentbab, we would like to send you a modest gift for finding this bug. Would you be open to sharing your name and mailing address? You can join our [community server](https://community.mattermost.com) and direct message me at ``@amy.blais``, OR you can send me an email at ``amy@mattermost.com``. Let me know what you think.
