### ISSUE TITLE
mattermost.service: main process exited with panic periodically

### ISSUE THREAD

**Issue by muirdok** [mattermost/mattermost-server#13240]
#### Summary
Mattermost server process goes to panic (probably after pushing notification)

#### Steps to reproduce
not attempted but it happens about once per week
```
Mattermost version: 5.17.0
Database version: 5.17.0
Database: postgres
```

#### Expected behavior
no panics

#### Observed behavior (that appears unintentional) 
```
ноя 28 11:01:12 chat mattermost[20696]: {"level":"info","ts":1574928072.8530402,"caller":"app/notification_push.go:291","msg":"Notification will be sent","logSource":"not
ноя 28 11:01:15 chat mattermost[20696]: {"level":"error","ts":1574928075.8535633,"caller":"app/notification_push.go:203","msg":"Notification error","logSource":"notificat
ноя 28 11:01:16 chat mattermost[20696]: panic: runtime error: invalid memory address or nil pointer dereference
ноя 28 11:01:16 chat mattermost[20696]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7b50a6]
ноя 28 11:01:16 chat mattermost[20696]: goroutine 10029651 [running]:
ноя 28 11:01:16 chat mattermost[20696]: github.com/mattermost/go-i18n/i18n/translation.(*template).Execute(0x0, 0x14289c0, 0xc0087bd230, 0x0, 0x4)
ноя 28 11:01:16 chat mattermost[20696]: /go/src/github.com/mattermost/mattermost-server/vendor/github.com/mattermost/go-i18n/i18n/translation/template.go:38 +0x26
ноя 28 11:01:16 chat.mattermost[20696]: github.com/mattermost/go-i18n/i18n/bundle.(*Bundle).translate(0xc00008f980, 0xc01380e020, 0x166e5f3, 0x31, 0xc008a8da40, 0x2, 0x2,
ноя 28 11:01:16 chat.mattermost[20696]: /go/src/github.com/mattermost/mattermost-server/vendor/github.com/mattermost/go-i18n/i18n/bundle/bundle.go:395 +0x1bf
ноя 28 11:01:16 chat.mattermost[20696]: github.com/mattermost/go-i18n/i18n/bundle.(*Bundle).TfuncAndLanguage.func1(0x166e5f3, 0x31, 0xc008a8da40, 0x2, 0x2, 0x40dfc8, 0x20
ноя 28 11:01:16 chat.mattermost[20696]: /go/src/github.com/mattermost/mattermost-server/vendor/github.com/mattermost/go-i18n/i18n/bundle/bundle.go:310 +0x65
ноя 28 11:01:16 chat.mattermost[20696]: github.com/mattermost/mattermost-server/utils.TfuncWithFallback.func1(0x166e5f3, 0x31, 0xc008a8da40, 0x2, 0x2, 0x0, 0x0)
ноя 28 11:01:17 chat.mattermost[20696]: /go/src/github.com/mattermost/mattermost-server/utils/i18n.go:124 +0x5f
ноя 28 11:01:17 chat mattermost[20696]: github.com/mattermost/mattermost-server/app.(*App).GetMessageForNotification(0xc0070fcfc0, 0xc005e7ea20, 0xc007825db0, 0x6, 0xc019
ноя 28 11:01:17 chat.attermost[20696]: /go/src/github.com/mattermost/mattermost-server/app/notification_email.go:342 +0x428
ноя 28 11:01:17 chat.mattermost[20696]: github.com/mattermost/mattermost-server/app.(*Server).renderBatchedPost(0xc0001d5800, 0xc0014c9d40, 0xc00922c000, 0xc009b70160, 0x
ноя 28 11:01:17 chat.mattermost[20696]: /go/src/github.com/mattermost/mattermost-server/app/email_batching.go:258 +0x19e
ноя 28 11:01:17 chat mattermost[20696]: github.com/mattermost/mattermost-server/app.(*Server).sendBatchedEmailNotification(0xc0001d5800, 0xc012fb6d20, 0x1a, 0xc01452ce40,
ноя 28 11:01:17 chat mattermost[20696]: /go/src/github.com/mattermost/mattermost-server/app/email_batching.go:226 +0x434
ноя 28 11:01:17 chat mattermost[20696]: github.com/mattermost/mattermost-server/app.(*EmailBatchingJob).checkPendingNotifications.func1.1()
ноя 28 11:01:17 chat mattermost[20696]: /go/src/github.com/mattermost/mattermost-server/app/email_batching.go:189 +0x55
ноя 28 11:01:17 chat mattermost[20696]: github.com/mattermost/mattermost-server/app.(*Server).Go.func1(0xc004b6d780, 0xc0001d5800)
ноя 28 11:01:17 chat mattermost[20696]: /go/src/github.com/mattermost/mattermost-server/app/server.go:377 +0x27
ноя 28 11:01:17 chat mattermost[20696]: created by github.com/mattermost/mattermost-server/app.(*Server).Go
ноя 28 11:01:17 chat mattermost[20696]: /go/src/github.com/mattermost/mattermost-server/app/server.go:376 +0x53
ноя 28 11:01:17 chat systemd[1]: mattermost.service: main process exited, code=exited, status=2/INVALIDARGUMENT
ноя 28 11:01:17 chat systemd[1]: Unit mattermost.service entered failed state.
ноя 28 11:01:17 chat systemd[1]: mattermost.service failed.
```

#### Possible fixes
not sure

**Comment by amyblais** [comment]
@muirdok Can you help with more information about your environment from here https://docs.mattermost.com/process/support.html#general-questions-for-any-issues?

**Comment by amyblais** [comment]
@muirdok Do you have an update on this? Do you have details on when this error usually occurs?

**Comment by amyblais** [comment]
We haven't received feedback on this for a while so I'll close this issue for now.

If the issue persists, I hope that you will re-open this issue with additional relevant information.

**Comment by muirdok** [comment]
Hm... I missed the notification.
@amyblais should I open new one or add details here?

**Comment by agnivade** [comment]
Reopening this one is sufficient. But your previous logs are cutoff from the right side. Please give us the entire logs along with the information asked here- https://docs.mattermost.com/process/support.html#general-questions-for-any-issues.
