### ISSUE TITLE
CLI SIGSEGV converting channel from private to public

### ISSUE THREAD

**Issue by Taffer** [mattermost/mattermost-server#13325]
#### Summary
Converting a channel from private to public via the CLI produces a SIGSEGV and succeeds.

#### Steps to reproduce
Server version 5.16.2, Database schema 5.16.0 hosted on Postgres
Host is Ubuntu 18.04.3 LTS.

ssh to server, and from the mattermost installation directory:

`sudo ./bin/mattermost channel modify my_team:existing_channel --username chris.herborth --public`

#### Expected behavior
I expect the channel to go from private to public.

#### Observed behavior (that appears unintentional) 
The channel went from private to public, but the CLI also produced this error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfacf02]

goroutine 1 [running]:
github.com/mattermost/mattermost-server/app.(*App).postChannelPrivacyMessage(0xc003a0b880, 0x0, 0xc0026ba4e0, 0x0)
	/go/src/github.com/mattermost/mattermost-server/app/channel.go:584 +0x2b2
github.com/mattermost/mattermost-server/app.(*App).UpdateChannelPrivacy(0xc003a0b880, 0xc0026ba4e0, 0x0, 0x0, 0x0)
	/go/src/github.com/mattermost/mattermost-server/app/channel.go:555 +0x6c
github.com/mattermost/mattermost-server/cmd/mattermost/commands.modifyChannelCmdF(0x29df060, 0xc000268740, 0x1, 0x4, 0x0, 0x0)
	/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/channel.go:522 +0x31a
github.com/spf13/cobra.(*Command).execute(0x29df060, 0xc0002686c0, 0x4, 0x4, 0x29df060, 0xc0002686c0)
	/go/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:826 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0x29d7360, 0x14d8715, 0xc0001b9f88, 0xc00009a058)
	/go/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:864
github.com/mattermost/mattermost-server/cmd/mattermost/commands.Run(...)
	/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/root.go:15
main.main()
	/go/src/github.com/mattermost/mattermost-server/cmd/mattermost/main.go:30 +0x89
```

#### Possible fixes
Sorry, I'm not much of a Go dev.

**Comment by amyblais** [comment]
Ticket here: https://mattermost.atlassian.net/browse/MM-21008.
