### ISSUE TITLE
Import from slack crashes due to invalid memory access or nil pointer dereference

### ISSUE THREAD

**Issue by mmohsenz** [mattermost/mattermost-server#13879]
#### Summary
Import from slack crashes due to invalid memory access or nil pointer dereference

#### Steps to reproduce
1. Created a slack corporate export for last 7 days (only 630KB)
2. Used mattermost cli to import the file as per migrating-from-slack-using-the-mattermost-cli documentation

Mattermost Version: 5.19.0
Running in docker based on https://github.com/mattermost/mattermost-docker

#### Expected behavior
Users, channels, and messages are imported into mattermost, or otherwise ignored if not supported.

#### Observed behavior (that appears unintentional) 
The mattermost cli crashes with a SIGSEGV. The users seem to all be imported; many channels and messages also appear.

The mattermost cli crashes as follow:

```
Running Slack Import. This may take a long time for large teams or teams with many messages.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x10920bd]

goroutine 1 [running]:
github.com/mattermost/mattermost-server/v5/app.(*App).OldImportChannel(0xc003781500, 0xc00278c680, 0xc0026a8540, 0x9, 0xc0026a8540, 0x9, 0x0, 0x0, 0xc0043ce900, 0x2, ...)
	github.com/mattermost/mattermost-server/v5@/app/slackimport.go:848 +0x41d
github.com/mattermost/mattermost-server/v5/app.(*App).SlackAddChannels(0xc003781500, 0xc00317fb40, 0x1a, 0xc004d34000, 0x390, 0x3bb, 0xc000029998, 0xc0025038f0, 0xc000029968, 0xc005b80b00, ...)
	github.com/mattermost/mattermost-server/v5@/app/slackimport.go:546 +0x76e
github.com/mattermost/mattermost-server/v5/app.(*App).SlackImport(0xc003781500, 0x18f1820, 0xc002525598, 0x9a763, 0xc00317fb40, 0x1a, 0x0, 0x0)
	github.com/mattermost/mattermost-server/v5@/app/slackimport.go:747 +0x1536
github.com/mattermost/mattermost-server/v5/cmd/mattermost/commands.slackImportCmdF(0x241d080, 0xc00026c840, 0x2, 0x2, 0x0, 0x0)
	github.com/mattermost/mattermost-server/v5@/cmd/mattermost/commands/import.go:77 +0x28c
github.com/spf13/cobra.(*Command).execute(0x241d080, 0xc00026c7a0, 0x2, 0x2, 0x241d080, 0xc00026c7a0)
	github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x2421400, 0x0, 0x64e00, 0xc00003a118)
	github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.5/command.go:864
github.com/mattermost/mattermost-server/v5/cmd/mattermost/commands.Run(...)
	github.com/mattermost/mattermost-server/v5@/cmd/mattermost/commands/root.go:15
main.main()
	github.com/mattermost/mattermost-server/v5@/cmd/mattermost/main.go:30 +0x87
```

#### Possible fixes
The issue is that some users are not supported and are skipped. Then during channel creation, dereferencing Id without checking whether the user exists causes the above crash.

```
diff --git a/app/slackimport.go b/app/slackimport.go
index a8fb13d26..f4fe6ee7c 100644
--- a/app/slackimport.go
+++ b/app/slackimport.go
@@ -846,7 +846,12 @@ func (a *App) OldImportUser(team *model.Team, user *model.User) *model.User {
 
 func (a *App) OldImportChannel(channel *model.Channel, sChannel SlackChannel, users map[string]*model.User) *model.Channel {
        if channel.Type == model.CHANNEL_DIRECT {
-               sc, err := a.createDirectChannel(users[sChannel.Members[0]].Id, users[sChannel.Members[1]].Id)
+               var user1 = users[sChannel.Members[0]]
+               var user2 = users[sChannel.Members[1]]
+               if user1 == nil || user2 == nil {
+                       return nil
+               }
+               sc, err := a.createDirectChannel(user1.Id, user2.Id)
                if err != nil {
                        return nil
                }
@@ -859,7 +864,11 @@ func (a *App) OldImportChannel(channel *model.Channel, sChannel SlackChannel, us
                members := make([]string, len(sChannel.Members))
 
                for i := range sChannel.Members {
-                       members[i] = users[sChannel.Members[i]].Id
+                       var user = users[sChannel.Members[i]]
+                       if user == nil {
+                               return nil
+                       }
+                       members[i] = user.Id
                }
 
                sc, err := a.createGroupChannel(members, users[sChannel.Creator].Id)
```

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-22560.

**Comment by luchaninov** [comment]
It happens when you have users from external teams.

You can edit `users.json` and add missing users manually.
Unzip your Slack export file and parse unique users.

```
<?php

$result = [];
$result['header'] = ['no', 'user_id', 'name', 'real_name', 'first_name', 'image_72', 'file'];

$f = fopen('users.tsv', 'wb');

$dirs = glob('*', GLOB_ONLYDIR);
$counter = 0;
foreach ($dirs as $dir) {
    $files = glob($dir . '/*');
    foreach ($files as $file) {
        $items = json_decode(file_get_contents($file), true);
        foreach ($items as $item) {
            $userId = $item['user'] ?? null;
            if ($userId !== null && !isset($result[$userId]) && isset($item['user_profile'])) {
                $profile = $item['user_profile'];
                $row = [
                    ++$counter,
                    $userId,
                    $profile['name'] ?? '',
                    $profile['real_name'] ?? '',
                    $profile['first_name'] ?? '',
                    $profile['image_72'] ?? '',
                    $file
                ];
                $result[$userId] = $row;

                echo(implode("\t", $row) . "\n");
                fwrite($f, implode("\t", $row) . "\n");
            }
        }
    }
}

fclose($f);
echo('ok');
```

**Comment by agnivade** [comment]
Thanks @mmohsenz. Your fix looks reasonable. I will be sending a PR soon.
