### ISSUE TITLE
Mattermost crash

### ISSUE THREAD

**Issue by OneFreelance** [mattermost/mattermost-server#14218]
#### Summary
panic: runtime error: invalid memory address or nil pointer dereference

#### Steps to reproduce
Unknown

#### Expected behavior
Server works without crashing

#### Observed behavior (that appears unintentional) 
```
Apr 01 07:13:27  mattermost[1273610]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 01 07:13:27  mattermost[1273610]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x981c76]
Apr 01 07:13:27  mattermost[1273610]: goroutine 1919477 [running]:
Apr 01 07:13:27  mattermost[1273610]: github.com/mattermost/mattermost-server/v5/model.(*AppError).Error(0x0, 0xc000032000, 0x177f060)
Apr 01 07:13:27  mattermost[1273610]:         github.com/mattermost/mattermost-server/v5@/model/utils.go:73 +0x26
Apr 01 07:13:27  mattermost[1273610]: go.uber.org/zap/zapcore.encodeError(0x1987ea8, 0x5, 0x1c7cb00, 0x0, 0x1cc93a0, 0xc00f7ac4e0, 0xc00
Apr 01 07:13:27  mattermost[1273610]:         go.uber.org/zap@v1.10.0/zapcore/error.go:46 +0x3b
Apr 01 07:13:27  mattermost[1273610]: go.uber.org/zap/zapcore.Field.AddTo(0x1987ea8, 0x5, 0x19, 0x0, 0x0, 0x0, 0x17c0500, 0x0, 0x1cc93a0
Apr 01 07:13:27  mattermost[1273610]:         go.uber.org/zap@v1.10.0/zapcore/field.go:165 +0xc8c
Apr 01 07:13:27  mattermost[1273610]: go.uber.org/zap/zapcore.addFields(0x1cc93a0, 0xc00f7ac4e0, 0xc010337c80, 0x2, 0x2)
Apr 01 07:13:27  mattermost[1273610]:         go.uber.org/zap@v1.10.0/zapcore/field.go:199 +0xcf
Apr 01 07:13:27  mattermost[1273610]: go.uber.org/zap/zapcore.(*jsonEncoder).EncodeEntry(0xc00209e390, 0x2, 0xbf993f39d687b601, 0xd177c4
Apr 01 07:13:27  mattermost[1273610]:         go.uber.org/zap@v1.10.0/zapcore/json_encoder.go:364 +0x1e4
Apr 01 07:13:27  mattermost[1273610]: go.uber.org/zap/zapcore.(*ioCore).Write(0xc00209e3c0, 0x2, 0xbf993f39d687b601, 0xd177c404256, 0x2a
Apr 01 07:13:27  mattermost[1273610]:         go.uber.org/zap@v1.10.0/zapcore/core.go:86 +0xa9
Apr 01 07:13:27  mattermost[1273610]: go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00caa2370, 0xc010337c80, 0x2, 0x2)
Apr 01 07:13:27  mattermost[1273610]:         go.uber.org/zap@v1.10.0/zapcore/entry.go:215 +0x117
Apr 01 07:13:27  mattermost[1273610]: go.uber.org/zap.(*Logger).Error(0xc0020ca300, 0x19cedec, 0x1f, 0xc010337c80, 0x2, 0x2)
Apr 01 07:13:27  mattermost[1273610]:         go.uber.org/zap@v1.10.0/logger.go:203 +0x7f
Apr 01 07:13:27  mattermost[1273610]: github.com/mattermost/mattermost-server/v5/mlog.(*Logger).Error(...)
Apr 01 07:13:27  mattermost[1273610]:         github.com/mattermost/mattermost-server/v5@/mlog/log.go:175
Apr 01 07:13:27  mattermost[1273610]: github.com/mattermost/mattermost-server/v5/app.(*App).CreatePost.func5()
Apr 01 07:13:27  mattermost[1273610]:         github.com/mattermost/mattermost-server/v5@/app/post.go:287 +0x233
Apr 01 07:13:27  mattermost[1273610]: github.com/mattermost/mattermost-server/v5/app.(*Server).Go.func1(0xc008b427e0, 0xc0004dce00)
Apr 01 07:13:27  mattermost[1273610]:         github.com/mattermost/mattermost-server/v5@/app/server.go:424 +0x27
Apr 01 07:13:27  mattermost[1273610]: created by github.com/mattermost/mattermost-server/v5/app.(*Server).Go
Apr 01 07:13:27  mattermost[1273610]:         github.com/mattermost/mattermost-server/v5@/app/server.go:423 +0x53
```

We have added `GOTRACEBACK=crash` as environment variable to systemd service, but since then server is working without crashing. If this issue will repeat - we will try to debug coredump and update this ticket

**Comment by amyblais** [comment]
@OneFreelance What Mattermost server version are you on?

**Comment by gyp5y** [comment]
Mattermost Version: 5.21.0
Database Schema Version: 5.21.0
Database: mysql
It's a two-node cluster

**Comment by agnivade** [comment]
Great catch. This is a shadowing bug. Fortunately this is now fixed in master with the search layer refactor.

**Comment by agnivade** [comment]
Hi @OneFreelance - I'll go ahead and close this one it's fixed in master. Please feel free to try any version from 5.22 onwards.
