### ISSUE TITLE
Typo in `WebsocketURL` protocol in config results in white screen when logged in

### ISSUE THREAD

**Issue by cguess** [mattermost/mattermost-server#15008]
#### Summary
If there is a typo in the the protocol (aka it's not `wss`) in the config file's `WebsocketURL` key the page will only render blank after logged in. 

#### Steps to reproduce
1. Type gibberish, or even a valid, non-`wss` (I think) url into the `WebsocketURL` key of the config file and restart the server.
1. Visit the page and log in, it'll be blank.

To fix, just leave it blank.

#### Expected behavior
An error when starting the server, or at least an error in the web interface. Basically, don't fail silently except in the web console.

#### Observed behavior (that appears unintentional) 
After restarting server with wrong url the page is blank and the following occurs in the javascript console:

```
websocket_client.jsx:38 Uncaught (in promise) DOMException: Failed to construct 'WebSocket': The URL's scheme must be either 'ws' or 'wss'. 'htt' is not allowed.
    at Object.initialize (https://mattermost.acdatacollective.org/static/6.961acb8ba98f2201d586.js:1:241161)
    at Object.K (https://mattermost.acdatacollective.org/static/6.961acb8ba98f2201d586.js:1:118948)
    at x.componentDidMount (https://mattermost.acdatacollective.org/static/2.e2af8304a4e224824c71.js:1:1777)
    at Di (https://mattermost.acdatacollective.org/static/main.6fb6ffa1d4c4a421b346.js:212:82146)
    at Pi (https://mattermost.acdatacollective.org/static/main.6fb6ffa1d4c4a421b346.js:212:85068)
    at https://mattermost.acdatacollective.org/static/main.6fb6ffa1d4c4a421b346.js:212:98146
    at Object.t.unstable_runWithPriority (https://mattermost.acdatacollective.org/static/main.6fb6ffa1d4c4a421b346.js:221:3198)
    at As (https://mattermost.acdatacollective.org/static/main.6fb6ffa1d4c4a421b346.js:212:98080)
    at Ts (https://mattermost.acdatacollective.org/static/main.6fb6ffa1d4c4a421b346.js:212:97856)
    at vs (https://mattermost.acdatacollective.org/static/main.6fb6ffa1d4c4a421b346.js:212:97201)
```

#### Possible fixes
Unsure how to fix it, but parsing and failing loudly on server start would probably be the best option.

**Comment by ahmaddanialmohd** [comment]
Hi, @cguess 

Verified and tested on 5.24.2 in which I **do not** have to reboot the server to reproduce the issue.

Setting the value to something like this:

```
ahmaddanial@mattermost:~$ cat /opt/mattermost/config/config.json | grep "WebsocketURL"
        "WebsocketURL": "https://something.mattermost.com",
```

![image](https://user-images.githubusercontent.com/49461314/87365058-d01d1a80-c5a7-11ea-842f-a95cb2743d21.png)

**Comment by amyblais** [comment]
Thanks, opened a ticket here: https://mattermost.atlassian.net/browse/MM-26895.

**Comment by amyblais** [comment]
@cguess Would you be open to either submitting a PR or opening a feature request for this? Our team mentioned that this is likely not something that will be prioritized in the near future (internally).
