### ISSUE TITLE
Joining team errors if default channel archived

### ISSUE THREAD

**Issue by dalcde** [mattermost/mattermost-server#15261]
#### Summary
If you archive a default channel in a team, joining the team causes an error

#### Steps to reproduce
1. Install Mattermost 5.26.0 (though I recall this occurring in older versions of Mattermost too)
2. Create a team
3. Remove the Off-Topic channel
4. Add a new user to the team

#### Expected behavior
The user joins the team

#### Observed behavior (that appears unintentional) 
An error occurs. The user successfully joins, but is stuck on the `/select_team` page until they log out and log in again.

Formatted error message:
```
{"level":"error","ts":1597391461.0306711,"caller":"http/server.go:3088","msg":"http: panic serving 127.0.0.1:43954: runtime error: invalid memory address or nil pointer dereference
goroutine 3613 [running]:
net/http.(*conn).serve.func1(0xc0019ec000)
        net/http/server.go:1800 +0x139
panic(0x1cec880, 0x346d3f0)
        runtime/panic.go:975 +0x3e3
github.com/mattermost/mattermost-server/v5/model.(*AppError).Error(...)
        github.com/mattermost/mattermost-server/v5/model/utils.go:73
github.com/mattermost/mattermost-server/v5/app.(*App).JoinDefaultChannels(0xc0047bde00, 0xc00486d820, 0x1a, 0xc001562000, 0x0, 0x0, 0x0, 0x8)
        github.com/mattermost/mattermost-server/v5/app/channel.go:85 +0xbe9
github.com/mattermost/mattermost-server/v5/app.(*App).JoinUserToTeam(0xc0047bde00, 0xc00188c8f0, 0xc001562000, 0x0, 0x0, 0xc001dec000)
        github.com/mattermost/mattermost-server/v5/app/team.go:669 +0x5f0
github.com/mattermost/mattermost-server/v5/app.(*App).AddUserToTeam(0xc0047bde00, 0xc00486d6c0, 0x1a, 0xc00486d6a0, 0x1a, 0x0, 0x0, 0x1f8302c, 0x4)
        github.com/mattermost/mattermost-server/v5/app/team.go:438 +0x230
github.com/mattermost/mattermost-server/v5/app.(*App).AddTeamMember(0xc0047bde00, 0xc00486d6c0, 0x1a, 0xc00486d6a0, 0x1a, 0x173ebf34715, 0x17486720f15)
        github.com/mattermost/mattermost-server/v5/app/team.go:805 +0x6b
github.com/mattermost/mattermost-server/v5/api4.addTeamMember(0xc0013f7f40, 0x237f640, 0xc0013f7f00, 0xc001546000)
        github.com/mattermost/mattermost-server/v5/api4/team.go:632 +0x5f0
github.com/mattermost/mattermost-server/v5/web.Handler.ServeHTTP(0xc000f1c610, 0x209b510, 0x31c91c8, 0xd, 0x10001, 0x0, 0x0, 0x2382740, 0xc00198ecb0, 0xc001546000)
        github.com/mattermost/mattermost-server/v5/web/handlers.go:240 +0x1d1a
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x2382180, 0xc0048621c0, 0xc001546000)
        github.com/NYTimes/gziphandler@v1.1.1/gzip.go:336 +0x211
net/http.HandlerFunc.ServeHTTP(0xc00196fbc0, 0x2382180, 0xc0048621c0, 0xc001546000)
        net/http/server.go:2041 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0002623c0, 0x2382180, 0xc0048621c0, 0xc0013a9d00)
        github.com/gorilla/mux@v1.7.4/mux.go:210 +0xe2
net/http.serverHandler.ServeHTTP(0xc0033460e0, 0x2382180, 0xc0048621c0, 0xc0013a9d00)
        net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc0019ec000, 0x238a600, 0xc0048e8640)
        net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
        net/http/server.go:2962 +0x35c","source":"httpserver"}
```

**Comment by amyblais** [comment]
@dalcde I wasn't able to reproduce. Does the user in step 4 get stuck even if there are multiple teams on the /select_team page for them to join?

**Comment by dalcde** [comment]
An error "Received invalid response from the server" shows up in the
select_team page when trying to join via the /select_team page, but
clicking "back" brings them back to the user interface.

The being stuck might also be a problem only if you join right after
signing up and verifying email.

In any case, the error shows up in the syslog.

**Comment by wiggin77** [comment]
The "off-Topic" channel is included in the list of default channels to join.  There is a bug in the code where that error condition (a default channel is deleted) causes a panic.  Another issue is that default channels are not checked for existence beforehand.

**Comment by amyblais** [comment]
Tickets
https://mattermost.atlassian.net/browse/MM-27868
https://mattermost.atlassian.net/browse/MM-27869
