### ISSUE TITLE
Errors after upgrading to 33.0

### ISSUE THREAD

**Issue by MiyazawaK** [mattermost/mattermost-server#17175]
#### Summary
After upgrading mattermost team edition to v33.0, mattermost logs tons of errors.

#### Steps to reproduce
Manually upgrading the system according to the manual.

#### Expected behavior
No errors

#### Observed behavior (that appears unintentional) 
Several errors per second, all look like this, but for different ips:
```
{"level":"error","ts":1616067130.0095673,"caller":"http/server.go:3093","msg":"http: panic serving 123.123.123.123:51886: could not get file descriptor\ngoroutine 2674649 [running]:\nnet/http.(*conn).serve.func1(0xc00394e460)\n\tnet/http/server.go:1801 +0x147\npanic(0x21c7fa0, 0xc00043ce60)\n\truntime/panic.go:975 +0x47a\ngithub.com/getsentry/sentry-go/http.(*Handler).recoverWithSentry(0xc000175460, 0xc002059530, 0xc00820d600)\n\tgithub.com/getsentry/sentry-go@v0.9.0/http/sentryhttp.go:117 +0x14f\npanic(0x21c7fa0, 0xc00043ce60)\n\truntime/panic.go:969 +0x1b9\ngithub.com/mailru/easygo/netpoll.Must(...)\n\tgithub.com/mailru/easygo@v0.0.0-20190618140210-3c14a0dc985f/netpoll/handle.go:40\ngithub.com/mattermost/mattermost-server/v5/app.(*WebConn).startPoller(0xc007d44f20)\n\tgithub.com/mattermost/mattermost-server/v5/app/web_conn.go:175 +0x11b\ngithub.com/mattermost/mattermost-server/v5/app.(*App).NewWebConn(0xc0065f3c20, 0x2946040, 0xc00611ce00, 0xc0075885e0, 0x1a, 0xc007588600, 0x1a, 0x17467cd1006, 0x178de8c0bc3, 0x1784517f96b, ...)\n\tgithub.com/mattermost/mattermost-server/v5/app/web_conn.go:91 +0x25a\ngithub.com/mattermost/mattermost-server/v5/api4.connectWebSocket(0xc0089def40, 0x291f6c0, 0xc0089def00, 0xc00820d800)\n\tgithub.com/mattermost/mattermost-server/v5/api4/websocket.go:47 +0x2e8\ngithub.com/mattermost/mattermost-server/v5/web.Handler.ServeHTTP(0xc0003623b0, 0x264ea58, 0x378d870, 0x10, 0x10000, 0x0, 0x0, 0x2922600, 0xc0020d80e0, 0xc00820d800)\n\tgithub.com/mattermost/mattermost-server/v5/web/handlers.go:264 +0x1d5c\ngithub.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x2922000, 0xc006976460, 0xc00820d800)\n\tgithub.com/NYTimes/gziphandler@v1.1.1/gzip.go:337 +0x225\nnet/http.HandlerFunc.ServeHTTP(0xc00393d0b0, 0x2922000, 0xc006976460, 0xc00820d800)\n\tnet/http/server.go:2042 +0x44\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc0000f8000, 0x2922000, 0xc006976460, 0xc00820d600)\n\tgithub.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3\ngithub.com/getsentry/sentry-go/http.(*Handler).handle.func1(0x2922000, 0xc006976460, 0xc00820d500)\n\tgithub.com/getsentry/sentry-go@v0.9.0/http/sentryhttp.go:103 +0x402\nnet/http.HandlerFunc.ServeHTTP(0xc002004b80, 0x2922000, 0xc006976460, 0xc00820d500)\n\tnet/http/server.go:2042 +0x44\nnet/http.serverHandler.ServeHTTP(0xc003a2a1c0, 0x2922000, 0xc006976460, 0xc00820d500)\n\tnet/http/server.go:2843 +0xa3\nnet/http.(*conn).serve(0xc00394e460, 0x292ac80, 0xc0089dee00)\n\tnet/http/server.go:1925 +0x8ad\ncreated by net/http.(*Server).Serve\n\tnet/http/server.go:2969 +0x36c","source":"httpserver"}
```

#### Additional Info
Our Server is behind a corporate proxy, but that wasn't an issue before.

Thanks in advance!

**Comment by amyblais** [comment]
@agnivade Is this related to https://github.com/mattermost/mattermost-server/pull/17172?

**Comment by MiyazawaK** [comment]
Just for info, I've installed and configured a reverse proxy (nginx) and now it seems to work fine.

**Comment by agnivade** [comment]
Yes, that's the issue. Sorry for the inconvenience @MiyazawaK.

**Comment by MiyazawaK** [comment]
Thanks for the quick reply! Should I close this issue, since installing the reverse proxy fixed the problem? Or are you closing it after the fix has been implemented?

**Comment by agnivade** [comment]
Sounds good then. I will close the issue since the fix has already been merged to master and backported. Dot release should be out soon.
