### ISSUE TITLE
Error: Cannot find module 'imagemin-gifsicle'

### ISSUE THREAD

**Issue by weeebdev** [mattermost/mattermost-server#17420]
#### Summary
Error: Cannot find module 'imagemin-gifsicle'

#### Steps to reproduce
```bash
git clone git@github.com:mattermost/mattermost-webapp.git
npm i
make dev
```

#### Expected behavior
Run without error

#### Observed behavior (that appears unintentional) 
```bash
ERROR in ./components/gif_picker/static/search_end.png
Module build failed (from ./node_modules/image-webpack-loader/index.js):
Error: Cannot find module 'imagemin-gifsicle'
Require stack:
- /home/adil/job/mattermost-webapp/node_modules/image-webpack-loader/index.js
- /home/adil/job/mattermost-webapp/node_modules/loader-runner/lib/loadLoader.js
- /home/adil/job/mattermost-webapp/node_modules/loader-runner/lib/LoaderRunner.js
- /home/adil/job/mattermost-webapp/node_modules/webpack/lib/NormalModule.js
- /home/adil/job/mattermost-webapp/node_modules/webpack/lib/NormalModuleFactory.js
- /home/adil/job/mattermost-webapp/node_modules/webpack/lib/Compiler.js
- /home/adil/job/mattermost-webapp/node_modules/webpack/lib/webpack.js
- /home/adil/job/mattermost-webapp/node_modules/webpack/lib/index.js
- /home/adil/job/mattermost-webapp/node_modules/webpack-cli/lib/webpack-cli.js
- /home/adil/job/mattermost-webapp/node_modules/webpack-cli/lib/bootstrap.js
- /home/adil/job/mattermost-webapp/node_modules/webpack-cli/bin/cli.js
- /home/adil/job/mattermost-webapp/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:923:15)
    at Function.Module._load (node:internal/modules/cjs/loader:768:27)
    at Module.require (node:internal/modules/cjs/loader:995:19)
    at require (/home/adil/job/mattermost-webapp/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.module.exports (/home/adil/job/mattermost-webapp/node_modules/image-webpack-loader/index.js:72:20)
 @ ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[2].use[2]!./components/gif_picker/components/SearchGrid/SearchGrid.scss 5:0-72 7:73-102
 @ ./components/gif_picker/components/SearchGrid/SearchGrid.scss 2:12-179 9:17-24 13:7-21 45:20-34 49:6-59:7 50:38-52 56:26-40 58:21-28 68:15-29 47:4-60:5
 @ ./components/gif_picker/components/SearchGrid/SearchGrid.jsx 30:0-27
 @ ./components/gif_picker/components/SearchGrid/index.js 22:0-38 36:62-72
 @ ./components/gif_picker/components/Search/index.jsx 26:0-69 73:44-54
 @ ./components/gif_picker/gif_picker.jsx 18:0-61 82:53-59
 @ ./components/emoji_picker/emoji_picker_tabs.jsx 21:0-61 113:42-51
 @ ./components/emoji_picker/emoji_picker_overlay.jsx 19:0-54 78:40-55
 @ ./components/edit_post_modal/edit_post_modal.jsx 30:0-82 454:99-117
 @ ./components/edit_post_modal/index.js 29:0-50 95:62-75
 @ ./components/channel_layout/channel_controller.jsx 20:0-55 80:159-172
 @ ./components/needs_team/needs_team.tsx 29:0-77 296:62-79
 @ ./components/needs_team/index.ts 33:0-37 76:73-82
 @ ./components/root/root.jsx 50:0-46 340:17-26
 @ ./components/root/index.js 19:0-30 45:62-66
 @ ./components/app.jsx 21:47-72
 @ ./root.jsx 22:0-33 53:52-55
```

### Possible fixes
```bash
cd ./node_modules/image-webpack-loader/
npm i imagemin-gifsicle
```

**Comment by skin-soc** [comment]
`npm install gifsicle` will resolve the issue

However, I cannot make webapp work with 5.34.1, it breaks system console once packaged and deployed...

**Comment by hmhealey** [comment]
What version of Node and NPM are you using? I had this happen a few times while I was testing upgrading to NPM v7, but it wasn't happening consistently.

**Comment by weeebdev** [comment]
Yeah, my problem was that I was using the wrong version of node. `nvm use 10.24.0` fixed it to me

**Comment by hmhealey** [comment]
@weeebdev Which version were you on previously when you saw the problem? We're actually in the process of upgrading to Node v14 everywhere, so hopefully the issue wasn't with that version

**Comment by weeebdev** [comment]
> @weeebdev Which version were you on previously when you saw the problem? We're actually in the process of upgrading to Node v14 everywhere, so hopefully the issue wasn't with that version

It was `v15`

**Comment by skin-soc** [comment]
The problem persists...

`npm -v`
6.14.11
'node -v`
v10.24.0

**Comment by weeebdev** [comment]
> The problem persists...
> 
> `npm -v`
> 6.14.11
> 
> `node -v`
> v10.24.0

Are you using Linux? Try `sudo apt-get install autoconf dh-autoreconf`. It worked for me before I changed the version
