### ISSUE TITLE
webapp - Error: Cannot find module 'gifsicle'

### ISSUE THREAD

**Issue by gusmcewan** [mattermost/mattermost-server#17452]
#### Summary
Packaging of webapp fails with `Error: Cannot find module 'gifsicle'`

#### Steps to reproduce

1. On a new `Ubuntu 20.04.02` VM, `mattermost-server` was deployed using relevant binary `5.34.2`
2. We forked and cloned `https://github.com/mattermost/mattermost-webapp`
3. We made **zero changes** to cloned repo
4. We ran `make package` to create `mattermost-webapp.tar.gz`

#### Expected behavior
Run without errors

#### Observed behavior (that appears unintentional) 
````
ERROR in ./sass/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/image-webpack-loader/index.js):
Error: Cannot find module 'gifsicle'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/gus/mattermost-webapp/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/gus/mattermost-webapp/node_modules/imagemin-gifsicle/index.js:3:18)
    at Module._compile (/home/gus/mattermost-webapp/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at processResult (/home/gus/mattermost-webapp/node_modules/webpack/lib/NormalModule.js:598:19)
    at runLoaders (/home/gus/mattermost-webapp/node_modules/webpack/lib/NormalModule.js:692:5)
    at /home/gus/mattermost-webapp/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /home/gus/mattermost-webapp/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at runSyncOrAsync (/home/gus/mattermost-webapp/node_modules/loader-runner/lib/LoaderRunner.js:156:3)
    at iterateNormalLoaders (/home/gus/mattermost-webapp/node_modules/loader-runner/lib/LoaderRunner.js:250:2)
    at /home/gus/mattermost-webapp/node_modules/loader-runner/lib/LoaderRunner.js:223:4
    at process._tickCallback (internal/process/next_tick.js:63:19)
 @ ./root.jsx 9:0-26
````
#### Possible fixes
`npm install gifsicle` resolved packaging issue. 

#### Further observed behavior (that appears unintentional) 

Using the possible temporary fix above, when `webapp` is deployed by:

1. Copying successfully created `mattermost-webapp-tar.gz` to the location where Mattermost is installed 
2. Remove the existing `client` folder
3. Running `tar -xvf mattermost-webapp.tar.gz` to extract new customized `client` folder
4. Restarting Mattermost server

we observe that `System Console` is broken, and instead of showing the full 43 menu options the `System Console` is limited to only the following options:

**USER MANAGEMENT**
- Users

**AUTHETICATION**
- AD/LDAP
- SAML 2.0

**PLUGINS (BETA)**
- Plugin Management
- Channel Export
- Incident Collaboration
- User Satisfaction Surveys

#### OS Defaults
OS: `Ubuntu 20.04.02`
npm: `6.14.4` 
node: `v10.19.0`

**Comment by amyblais** [comment]
@gusmcewan This seems to be the same as https://github.com/mattermost/mattermost-server/issues/17420. Do the comments there help?

**Comment by gusmcewan** [comment]
@amyblais Aware, checked closed comments first, unfortunately not a solution in #17420 for us.

**Comment by amyblais** [comment]
@hmhealey Would you be able to help with this?

**Comment by hmhealey** [comment]
That's strange that it didn't install gifsicle. I know newer versions of Node had issues with that like in the other linked issue, but we haven't seen that happen on Node 10 before. Perhaps it was just a momentary issue?

As for the missing categories in the system console, that's caused by the server and web app versions being out of sync. From what I understand, there were some permission changes that the web app likely expects that the server isn't providing. That should be fixed on the latest version of the webapp's master branch, but we'd recommend you use a previous version of the web app that matches your server version. Each release version is built from its corresponding `release-X.Y` branch, so you'd want to build your custom web app using the `release-5.34` branch.

**Comment by gusmcewan** [comment]
Reverting to `https://github.com/mattermost/mattermost-webapp/tree/release-5.34` solved this problem.

Missing `gifsicle` module remains an issue but solved by manual installation and repackaging.

Thank you.
