### ISSUE TITLE
Mattermost team crashes unexpectedly after upgrade from 5.32.0 to 5.35.1

### ISSUE THREAD

**Issue by muirdok** [mattermost/mattermost-server#17699]
#### Summary
After upgrade version from 5.32.0 to 5.35.1 it works well until clients (different versions and type) connect and do some "payload". Like I updated it in midnight and it got crashed at 10 a.m. After restarting it crashed again. I rolled back changes to 5.32.0 and it works normal now. Not sure what client crashes server.
Upgrade process with updating postgres database seemed to be normal.
Some debug info:

Service:

- Mattermost server (teams): 5.32.0
- Database schema: 5.32.0
- Database postgres

Host:

- Linux matt.domain.com 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- CentOS Linux release 7.9.2009 (Core)
- postgresql10-libs-10.17-1PGDG.rhel7.x86_64
- ostgresql10-10.17-1PGDG.rhel7.x86_64
- postgresql10-server-10.17-1PGDG.rhel7.x86_64

#### Steps to reproduce
1) Stop 5.32.0 service
2) Move 5.32.0 folder to backup
3) Download and extract https://releases.mattermost.com/5.35.1/mattermost-team-5.35.1-linux-amd64.tar.gz
4) Copy config.json from 5.32.0 folder to 5.35.1
5) Chmod\chown for 5.35.1
6) Run 5.35.1 service
7) Check status
8) Wait fo it

#### Expected behavior
Works perfect as usually

#### Observed behavior (that appears unintentional) 
Crash (full log of panic is 512Kb):
```
-- Logs begin at Tue 2021-05-11 12:15:19 MSK, end at Tue 2021-06-01 12:52:44 MSK. --
May 31 10:00:44 chat.matt.domain.comce.com mattermost[23923]: panic: loading {20 0}: found {19 0}
May 31 10:00:44 chat.matt.domain.comce.com mattermost[23923]: goroutine 624107 [running]:
May 31 10:00:44 chat.matt.domain.comce.com mattermost[23923]: panic(0x24243e0, 0xc006341bd0)
May 31 10:00:44 chat.matt.domain.comce.com mattermost[23923]: runtime/panic.go:1064 +0x545 fp=0xc0067535c8 sp=0xc006753500 pc=0x439705
May 31 10:00:44 chat.matt.domain.comce.com mattermost[23923]: github.com/ledongthuc/pdf.(*Reader).resolve(0xc007a71b60, 0x0, 0x25205c0, 0xc00282be00, 0xc00a4a5058, 0x0, 0x1000, 0xc006753928)
May 31 10:00:44 chat.matt.domain.comce.com mattermost[23923]: github.com/ledongthuc/pdf@v0.0.0-20200323191019-23c5852adbd2/read.go:768 +0xdd6 fp=0xc006753878 sp=0xc0067535c8 pc=0x1763db6

xxxxxxxxx not sure how to attah full log of panic 512Kb xxxxxxxxx

1 10:00:46 chat.matt.domain.comce.com mattermost[23923]: <autogenerated>:1 +0xc5 fp=0xc004d7d898 sp=0xc004d7d800 pc=0x209b145
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x2c10180, 0xc00281f180, 0xc006a75f00)
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: github.com/NYTimes/gziphandler@v1.1.1/gzip.go:337 +0x225 fp=0xc004d7d938 sp=0xc004d7d898 pc=0x1ec5f85
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: net/http.HandlerFunc.ServeHTTP(0xc00285c720, 0x2c10180, 0xc00281f180, 0xc006a75f00)
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: net/http/server.go:2042 +0x44 fp=0xc004d7d960 sp=0xc004d7d938 pc=0x7272a4
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc000188240, 0x2c10180, 0xc00281f180, 0xc006a75d00)
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3 fp=0xc004d7da98 sp=0xc004d7d960 pc=0x1774833
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: github.com/getsentry/sentry-go/http.(*Handler).handle.func1(0x2c10180, 0xc00281f180, 0xc006a75c00)
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: github.com/getsentry/sentry-go@v0.10.0/http/sentryhttp.go:103 +0x402 fp=0xc004d7dbc8 sp=0xc004d7da98 pc=0x17f8442
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: net/http.HandlerFunc.ServeHTTP(0xc00425a740, 0x2c10180, 0xc00281f180, 0xc006a75c00)
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: net/http/server.go:2042 +0x44 fp=0xc004d7dbf0 sp=0xc004d7dbc8 pc=0x7272a4
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: net/http.serverHandler.ServeHTTP(0xc0029d61c0, 0x2c10180, 0xc00281f180, 0xc006a75c00)
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: net/http/server.go:2843 +0xa3 fp=0xc004d7dc20 sp=0xc004d7dbf0 pc=0x72a9a3
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: net/http.(*conn).serve(0xc0077d2140, 0x2c19e80, 0xc0094ee640)
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: net/http/server.go:1925 +0x8ad fp=0xc004d7dfc8 sp=0xc004d7dc20 pc=0x7260ad
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: runtime.goexit()
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: runtime/asm_amd64.s:1374 +0x1 fp=0xc004d7dfd0 sp=0xc004d7dfc8 pc=0x472ca1
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: created by net/http.(*Server).Serve
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: net/http/server.go:2969 +0x36c
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: goroutine 623133 [select]:
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: runtime.gopark(0x2914e48, 0x0, 0x1809, 0x1)
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: runtime/proc.go:306 +0xe5 fp=0xc0028b2b58 sp=0xc0028b2b38 pc=0x43c705
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: runtime.selectgo(0xc0028b2ed0, 0xc0028b2d08, 0x4, 0x3, 0x801)
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: runtime/select.go:338 +0xcef fp=0xc0028b2c80 sp=0xc0028b2b58 pc=0x44ca4f
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: github.com/mattermost/mattermost-server/v5/app.(*WebConn).writePump(0xc001946d00)
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: github.com/mattermost/mattermost-server/v5/app/web_conn.go:219 +0x23a fp=0xc0028b2fa0 sp=0xc0028b2c80 pc=0x1e9441a
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: github.com/mattermost/mattermost-server/v5/app.(*WebConn).Pump.func1(0xc0081ed490, 0xc001946d00)
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: github.com/mattermost/mattermost-server/v5/app/web_conn.go:160 +0x53 fp=0xc0028b2fd0 sp=0xc0028b2fa0 pc=0x1ebb313
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: runtime.goexit()
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: runtime/asm_amd64.s:1374 +0x1 fp=0xc0028b2fd8 sp=0xc0028b2fd0 pc=0x472ca1
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: created by github.com/mattermost/mattermost-server/v5/app.(*WebConn).Pump
May 31 10:00:46 chat.matt.domain.comce.com mattermost[23923]: github.com/mattermost/mattermost-server/v5/app/web_conn.go:158 +0x86
```

#### Possible fixes
not attempted

**Comment by streamer45** [comment]
@amyblais 

Judging by the logs this looks like https://mattermost.atlassian.net/browse/MM-35990

**Comment by muirdok** [comment]
@streamer45 I can send\attach full crash log somethere if needs

**Comment by streamer45** [comment]
> @streamer45 I can send\attach full crash log somethere if needs

Thanks @muirdok that would be great.

**Comment by muirdok** [comment]
@streamer45 sent it to cstcld91@gmail.com
Thank you!

**Comment by streamer45** [comment]
Had a look at the full log and can confirm it's the same issue which is getting fixed as we speak.

**Comment by muirdok** [comment]
@streamer45 thanks!
As I see "pdftotext issue" marked as resolved. Does it mean we could expect fix in new release of mattermost?

**Comment by streamer45** [comment]
> @streamer45 thanks!
> As I see "pdftotext issue" marked as resolved. Does it mean we could expect fix in new release of mattermost?

Correct, a new dot release should be out soon with the fix for this.

**Comment by amyblais** [comment]
5.35.2 dot release is now available with this fix,
