### ISSUE TITLE
Runtime Error after upgrading from 5.33 to 5.37

### ISSUE THREAD

**Issue by bujinin** [mattermost/mattermost-server#18017]
#### Summary
Upgraded from 5.33.0 to 5.37.0 yesterday, basically everything is working but the logs show a runtime error (pasted below).

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
Upgrade to 5.37.0 using a nginx reverse proxy (and using a corporate proxy for the server if that matters)

#### Expected behavior
No errors in the logs

#### Observed behavior (that appears unintentional) 
Couple of these messages per day (maybe 20 today?)
```
{"level":"error","ts":1627463273.4415634,"caller":"http/server.go:3093","msg":"http: panic serving 1.2.3.4:50822: runtime error: invalid memory address or nil pointer dereference\ngoroutine 409363 [running]:\nnet/http.(*conn).serve.func1(0xc005ff0000)\n\tnet/http/server.go:1801 +0x147\npanic(0x2521aa0, 0x3f2d9d0)\n\truntime/panic.go:975 +0x47a\ngithub.com/getsentry/sentry-go/http.(*Handler).recoverWithSentry(0xc006023f10, 0xc004e83da0, 0xc004608800)\n\tgithub.com/getsentry/sentry-go@v0.11.0/http/sentryhttp.go:117 +0x14f\npanic(0x2521aa0, 0x3f2d9d0)\n\truntime/panic.go:969 +0x1b9\ngithub.com/mattermost/mattermost-server/v5/api4.getPrevTrialLicense(0xc007e89640, 0x2cf16e0, 0xc007e89600, 0xc004608a00)\n\tgithub.com/mattermost/mattermost-server/v5/api4/license.go:278 +0x63\ngithub.com/mattermost/mattermost-server/v5/web.Handler.ServeHTTP(0x2d679a0, 0xc0003a92a0, 0x29d65a8, 0x3ceacd8, 0x13, 0x100000001, 0x0, 0x0, 0x2cf4660, 0xc005367180, ...)\n\tgithub.com/mattermost/mattermost-server/v5/web/handlers.go:298 +0x1db2\ngithub.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x2cf4060, 0xc007ce2460, 0xc004608a00)\n\tgithub.com/NYTimes/gziphandler@v1.1.1/gzip.go:337 +0x225\nnet/http.HandlerFunc.ServeHTTP(0xc00564c840, 0x2cf4060, 0xc007ce2460, 0xc004608a00)\n\tnet/http/server.go:2042 +0x44\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc000188240, 0x2cf4060, 0xc007ce2460, 0xc004608800)\n\tgithub.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3\ngithub.com/getsentry/sentry-go/http.(*Handler).handle.func1(0x2cf4060, 0xc007ce2460, 0xc004608700)\n\tgithub.com/getsentry/sentry-go@v0.11.0/http/sentryhttp.go:103 +0x402\nnet/http.HandlerFunc.ServeHTTP(0xc00603e520, 0x2cf4060, 0xc007ce2460, 0xc004608700)\n\tnet/http/server.go:2042 +0x44\nnet/http.serverHandler.ServeHTTP(0xc0004a35e0, 0x2cf4060, 0xc007ce2460, 0xc004608700)\n\tnet/http/server.go:2843 +0xa3\nnet/http.(*conn).serve(0xc005ff0000, 0x2cfdf20, 0xc007e89540)\n\tnet/http/server.go:1925 +0x8ad\ncreated by net/http.(*Server).Serve\n\tnet/http/server.go:2969 +0x36c","source":"httpserver"}
```

#### Possible fixes
I hope you have an idea :) Thx!

**Comment by bujinin** [comment]
Could figure it out myself - it's a known issue:
https://docs.mattermost.com/install/self-managed-changelog.html#known-issues
