### ISSUE TITLE
"runtime error: invalid memory address or nil pointer dereference" happened for  version 5.38.1

### ISSUE THREAD

**Issue by muirdok** [mattermost/mattermost-server#18241]
#### Summary
Mattermost crashed with error "panic: runtime error: invalid memory address or nil pointer dereference".
Mattermost:
- Version Mattermost: 5.38.1
- Database schema: 5.38.1
- Database: postgres
host:
Linux chat.test.test 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
CentOS Linux release 7.9.2009 (Core)

part of huge stacktrace log:
`авг 23 09:15:19 chat.test.test mattermost[1622]: panic: runtime error: invalid memory address or nil pointer dereference
авг 23 09:15:19 chat.test.test mattermost[1622]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0xf930b6]
авг 23 09:15:19 chat.test.test mattermost[1622]: goroutine 2631221 [running]:
авг 23 09:15:19 chat.test.test mattermost[1622]: panic(0x26479e0, 0x4102240)
авг 23 09:15:19 chat.test.test mattermost[1622]: runtime/panic.go:1064 +0x545 fp=0xc00418f760 sp=0xc00418f698 pc=0x439725
авг 23 09:15:19 chat.test.test mattermost[1622]: runtime.panicmem(...)
авг 23 09:15:19 chat.test.test mattermost[1622]: runtime/panic.go:212
авг 23 09:15:19 chat.test.test mattermost[1622]: runtime.sigpanic()
авг 23 09:15:19 chat.test.test mattermost[1622]: runtime/signal_unix.go:742 +0x413 fp=0xc00418f790 sp=0xc00418f760 pc=0x4504d3
авг 23 09:15:19 chat.test.test mattermost[1622]: archive/zip.(*File).findBodyOffset(0x0, 0x7f96cc3be068, 0x0, 0xf2fe)
авг 23 09:15:19 chat.test.test mattermost[1622]: archive/zip/reader.go:233 +0x36 fp=0xc00418f800 sp=0xc00418f790 pc=0xf930b6
авг 23 09:15:19 chat.test.test mattermost[1622]: archive/zip.(*File).Open(0x0, 0xf2fe, 0xc009168000, 0xf2fe, 0xc009168000)
авг 23 09:15:19 chat.test.test mattermost[1622]: archive/zip/reader.go:157 +0x45 fp=0xc00418f8a0 sp=0xc00418f800 pc=0xf92945
авг 23 09:15:19 chat.test.test mattermost[1622]: code.sajari.com/docconv.parseDocxText(0x0, 0x0, 0x0, 0x0, 0x0)
авг 23 09:15:19 chat.test.test mattermost[1622]: code.sajari.com/docconv@v1.1.1-0.20200701232649-d9ea05fbd50a/docx.go:139 +0x66 fp=0xc00418f9c0 sp=0xc00418f8a0 pc=0x18d14c6
авг 23 09:15:19 chat.test.test mattermost[1622]: code.sajari.com/docconv.ConvertDocx(0x2e40ae0, 0xc0055172f8, 0x0, 0x0, 0x0, 0x0, 0x0)
авг 23 09:15:19 chat.test.test mattermost[1622]: code.sajari.com/docconv@v1.1.1-0.20200701232649-d9ea05fbd50a/docx.go:104 +0x56e fp=0xc00418fbb0 sp=0xc00418f9c0 pc=0x18d05ae
авг 23 09:15:19 chat.test.test mattermost[1622]: github.com/mattermost/mattermost-server/v5/services/docextractor.(*documentExtractor).Extract(0x4194cf0, 0xc00662b460, 0x17, 0x2e651e0, 0xc0055172f8, 0x0, 0x18f7533, 0x2627b60, 0xc00055ddd0)
авг 23 09:15:19 chat.test.test mattermost[1622]: github.com/mattermost/mattermost-server/v5/services/docextractor/documents.go:41 +0x102 fp=0xc00418fc10 sp=0xc00418fbb0 pc=0x18f76a2
авг 23 09:15:19 chat.test.test mattermost[1622]: github.com/mattermost/mattermost-server/v5/services/docextractor.(*combineExtractor).Extract(0xc00621fa40, 0xc00662b460, 0x17, 0x2e651e0, 0xc0055172f8, 0xc00d818400, 0x2, 0x4, 0x2e651e0)
авг 23 09:15:19 chat.test.test mattermost[1622]: github.com/mattermost/mattermost-server/v5/services/docextractor/combine.go:33 +0x142 fp=0xc00418fce0 sp=0xc00418fc10 pc=0x18f6b22
авг 23 09:15:19 chat.test.test mattermost[1622]: github.com/mattermost/mattermost-server/v5/services/docextractor.ExtractWithExtraExtractors(0xc00662b460, 0x17, 0x2e651e0, 0xc0055172f8, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0063fce08, ...)
авг 23 09:15:19 chat.test.test mattermost[1622]: github.com/mattermost/mattermost-server/v5/services/docextractor/docextractor.go:43 +0x2d4 fp=0xc00418fd88 sp=0xc00418fce0 pc=0x18f6f54
авг 23 09:15:19 chat.test.test mattermost[1622]: github.com/mattermost/mattermost-server/v5/services/docextractor.Extract(...)
авг 23 09:15:19 chat.test.test mattermost[1622]: github.com/mattermost/mattermost-server/v5/services/docextractor/docextractor.go:19
авг 23 09:15:19 chat.test.test mattermost[1622]: github.com/mattermost/mattermost-server/v5/app.(*App).ExtractContentFromFileInfo(0xc001cf04b0, 0xc007f9c600, 0x0, 0x0)
авг 23 09:15:19 chat.test.test mattermost[1622]: github.com/mattermost/mattermost-server/v5/app/file.go:1346 +0x1f7 fp=0xc00418fea8 sp=0xc00418fd88 pc=0x1f242b7
авг 23 09:15:19 chat.test.test mattermost[1622]: github.com/mattermost/mattermost-server/v5/app.(*App).UploadFileX.func1()
авг 23 09:15:19 chat.test.test mattermost[1622]: github.com/mattermost/mattermost-server/v5/app/file.go:776 +0x4a fp=0xc00418ffa8 sp=0xc00418fea8 pc=0x2042a4a
авг 23 09:15:19 chat.test.test mattermost[1622]: github.com/mattermost/mattermost-server/v5/app.(*Server).Go.func1(0xc00621fa00, 0xc001733200)
авг 23 09:15:19 chat.test.test mattermost[1622]: github.com/mattermost/mattermost-server/v5/app/server.go:1131 +0x27 fp=0xc00418ffd0 sp=0xc00418ffa8 pc=0x204f8e7
авг 23 09:15:19 chat.test.test mattermost[1622]: runtime.goexit()`

#### Steps to reproduce
not attempted 
it crashed unexpectedly with different time periods (only under "payload" when users start using it)

#### Expected behavior
it doesn't panic

#### Observed behavior (that appears unintentional) 
it panics 

#### Possible fixes
dunno 
it scared m

**Comment by muirdok** [comment]
I disabled all webhooks and integrations to check behaviour.

**Comment by yedamao** [comment]
[archive/zip: can panic when calling Reader.Open [Go 1.16]](https://github.com/golang/go/issues/44917) The panic has been fixed since go 1.16.1

**Comment by muirdok** [comment]
Thank you @yedamao! It explains the panic.
But in case it has been fixed since go 1.16.1 why it panicked 5.38.1 mattermost? 
I updated whole service from https://releases.mattermost.com/5.38.1/mattermost-team-5.38.1-linux-amd64.tar.gz
Do we have any workaround  here?

**Comment by streamer45** [comment]
Hi @muirdok, Looks like Mattermost 5.38.1 Team Edition has been built with Go version `1.15.5`. Since you are using team edition you could build it from source using a more recent Go version. In the meantime I'll see if we can update the build.
