### ISSUE TITLE
mattermost extract-documents-content - panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bbodenmiller** [mattermost/mattermost-server#18753]
#### Summary
Received `panic: runtime error: invalid memory address or nil pointer dereference` during `mattermost extract-documents-content` run which exited extraction process mid-run

#### Steps to reproduce
Running 5.38.2. Unclear how to reproduce.

#### Expected behavior
No error or at minimum graceful skipping of this file rather than crashing `extract-documents-content` process

#### Observed behavior (that appears unintentional) 
```
extracting file something.pptx x/teams/noteam/channels/x/users/x/x/something.pptx
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0xeeadf6]

goroutine 1 [running]:
archive/zip.(*File).findBodyOffset(0x0, 0xc005a27620, 0x0, 0x1000)
        archive/zip/reader.go:260 +0x36
archive/zip.(*File).Open(0x0, 0xc006d4d200, 0x0, 0xc000039760, 0xeeee35)
        archive/zip/reader.go:180 +0x45
code.sajari.com/docconv.parseDocxText(0x0, 0x0, 0x0, 0x0, 0x0)
        code.sajari.com/docconv@v1.1.1-0.20200701232649-d9ea05fbd50a/docx.go:139 +0x66
code.sajari.com/docconv.ConvertPptx(0x2d378c0, 0xc0011aa900, 0xc0011aa900, 0x2d378c0, 0xc0011aa900, 0x1, 0xc0026bcf50)
        code.sajari.com/docconv@v1.1.1-0.20200701232649-d9ea05fbd50a/pptx.go:59 +0x449
github.com/mattermost/mattermost-server/v5/services/docextractor.(*documentExtractor).Extract(0x3ffed58, 0xc007d9fdd0, 0x17, 0x7f7928e89378, 0xc0011aa900, 0x0, 0x40, 0xc0000399f0, 0x183f9f4)
        github.com/mattermost/mattermost-server/v5/services/docextractor/documents.go:41 +0x122
github.com/mattermost/mattermost-server/v5/services/docextractor.(*combineExtractor).Extract(0xc0074d2108, 0xc007d9fdd0, 0x17, 0x7f7928e89378, 0xc0011aa900, 0xc0010fc000, 0x2, 0x4, 0x7f7928e89378)
        github.com/mattermost/mattermost-server/v5/services/docextractor/combine.go:33 +0x142
github.com/mattermost/mattermost-server/v5/services/docextractor.ExtractWithExtraExtractors(0xc007d9fdd0, 0x17, 0x7f7928e89378, 0xc0011aa900, 0x1, 0x0, 0x0, 0x0, 0x0, 0xc000039b70, ...)
        github.com/mattermost/mattermost-server/v5/services/docextractor/docextractor.go:43 +0x2d3
github.com/mattermost/mattermost-server/v5/services/docextractor.Extract(...)
        github.com/mattermost/mattermost-server/v5/services/docextractor/docextractor.go:19
github.com/mattermost/mattermost-server/v5/app.(*App).ExtractContentFromFileInfo(0xc001e7e840, 0xc004f80200, 0x0, 0x0)
        github.com/mattermost/mattermost-server/v5/app/file.go:1346 +0x1f8
github.com/mattermost/mattermost-server/v5/cmd/mattermost/commands.extractContentCmdF(0x3f8a160, 0xc000543940, 0x0, 0x2, 0x0, 0x0)
        github.com/mattermost/mattermost-server/v5/cmd/mattermost/commands/extract_content.go:82 +0x3c5
github.com/spf13/cobra.(*Command).execute(0x3f8a160, 0xc000543920, 0x2, 0x2, 0x3f8a160, 0xc000543920)
        github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x3f90f60, 0x0, 0xffffffff, 0xc00010e058)
        github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.3/command.go:897
github.com/mattermost/mattermost-server/v5/cmd/mattermost/commands.Run(...)
        github.com/mattermost/mattermost-server/v5/cmd/mattermost/commands/root.go:14
main.main()
        github.com/mattermost/mattermost-server/v5/cmd/mattermost/main.go:31 +0x86
```

#### Possible fixes
Unknown

**Comment by bbodenmiller** [comment]
Looks fixed in 5.39.2.
