### ISSUE TITLE
SIGSEGV after upgrade from 6.1.0 to 6.2.0

### ISSUE THREAD

**Issue by TwizzyDizzy** [mattermost/mattermost-server#19189]
#### Summary

After upgrading from `6.1.0` to `6.2.0`, the server doesn't start anymore, logging SIGSEGV errors pointing into the direction of a null pointer exception.

#### Steps to reproduce

Not clear at this point.

#### Expected behavior

Server should start without dying.

#### Observed behavior (that appears unintentional) 

**From a `systemd` perspective:**
```
Dec 15 18:40:36 myhostname systemd[1]: mattermost.service: Consumed 57min 6.901s CPU time.
<<< Mattermost 6.1.0 has been stopped here
Dec 15 18:40:44 myhostname systemd[1]: Started Mattermost is an open source, self-hosted Slack-alternative.
Dec 15 18:41:00 myhostname mattermost[1781247]: panic: runtime error: invalid memory address or nil pointer dereference [recovered]
Dec 15 18:41:00 myhostname mattermost[1781247]:         panic: runtime error: invalid memory address or nil pointer dereference
Dec 15 18:41:00 myhostname mattermost[1781247]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x13c0c87]
Dec 15 18:41:00 myhostname mattermost[1781247]: goroutine 1 [running]:
Dec 15 18:41:00 myhostname mattermost[1781247]: panic(0x2874020, 0x44cd2b0)
Dec 15 18:41:00 myhostname mattermost[1781247]:         runtime/panic.go:1065 +0x565 fp=0xc0019c5050 sp=0xc0019c4f88 pc=0x439cc5
Dec 15 18:41:00 myhostname mattermost[1781247]: github.com/mattermost/mattermost-server/v6/cmd/mattermost/commands.runServer.func1()
Dec 15 18:41:00 myhostname mattermost[1781247]:         github.com/mattermost/mattermost-server/v6/cmd/mattermost/commands/server.go:92 +0x385 fp=0xc0019c5178 sp=0xc0019c5050 pc=0x24eab25
Dec 15 18:41:00 myhostname mattermost[1781247]: runtime.call16(0x0, 0x2d639f8, 0xc0044b3ee8, 0x0)
Dec 15 18:41:00 myhostname mattermost[1781247]:         runtime/asm_amd64.s:550 +0x3e fp=0xc0019c5198 sp=0xc0019c5178 pc=0x472c9e
Dec 15 18:41:00 myhostname mattermost[1781247]: runtime.reflectcallSave(0xc0019c52d0, 0x2d639f8, 0xc0044b3ee8, 0x100000000000000)
Dec 15 18:41:00 myhostname mattermost[1781247]:         runtime/panic.go:877 +0x58 fp=0xc0019c51c8 sp=0xc0019c5198 pc=0x439698
Dec 15 18:41:00 myhostname mattermost[1781247]: runtime.runOpenDeferFrame(0xc000000180, 0xc0044b3ea0, 0xc0019c5318)
Dec 15 18:41:00 myhostname mattermost[1781247]:         runtime/panic.go:851 +0x62d fp=0xc0019c5250 sp=0xc0019c51c8 pc=0x43936d
Dec 15 18:41:00 myhostname mattermost[1781247]: panic(0x2874020, 0x44cd2b0)
Dec 15 18:41:00 myhostname mattermost[1781247]:         runtime/panic.go:965 +0x1b9 fp=0xc0019c5318 sp=0xc0019c5250 pc=0x439919
Dec 15 18:41:00 myhostname mattermost[1781247]: runtime.panicmem()
Dec 15 18:41:00 myhostname mattermost[1781247]:         runtime/panic.go:212 +0x5b fp=0xc0019c5338 sp=0xc0019c5318 pc=0x437d1b
Dec 15 18:41:00 myhostname mattermost[1781247]: runtime.sigpanic()
Dec 15 18:41:00 myhostname mattermost[1781247]:         runtime/signal_unix.go:734 +0x173 fp=0xc0019c5370 sp=0xc0019c5338 pc=0x451a13
Dec 15 18:41:00 myhostname mattermost[1781247]: github.com/mattermost/mattermost-server/v6/plugin.(*Environment).TogglePluginHealthCheckJob(0x0, 0xc002737001)
Dec 15 18:41:00 myhostname mattermost[1781247]:         github.com/mattermost/mattermost-server/v6/plugin/environment.go:511 +0x47 fp=0xc0019c5440 sp=0xc0019c5370 pc=0x13c0c87
Dec 15 18:41:00 myhostname mattermost[1781247]: github.com/mattermost/mattermost-server/v6/app.(*Channels).initPlugins(0xc0002ce5a0, 0xc003e86d00, 0xc002725360, 0x9, 0xc002725370, 0x10)
Dec 15 18:41:00 myhostname mattermost[1781247]:         github.com/mattermost/mattermost-server/v6/app/plugin.go:179 +0xcf fp=0xc0019c55c0 sp=0xc0019c5440 pc=0x20bc6cf
Dec 15 18:41:00 myhostname mattermost[1781247]: github.com/mattermost/mattermost-server/v6/app.(*Channels).Start(0xc0002ce5a0, 0xc001cf6120, 0xc0019c5b88)
Dec 15 18:41:00 myhostname mattermost[1781247]:         github.com/mattermost/mattermost-server/v6/app/channels.go:65 +0x11b fp=0xc0019c5630 sp=0xc0019c55c0 pc=0x201031b
Dec 15 18:41:00 myhostname mattermost[1781247]: github.com/mattermost/mattermost-server/v6/app.(*Server).Start(0xc000500c00, 0xc0029e8790, 0x5)
Dec 15 18:41:00 myhostname mattermost[1781247]:         github.com/mattermost/mattermost-server/v6/app/server.go:1206 +0xe9 fp=0xc0019c5c78 sp=0xc0019c5630 pc=0x2113a89
Dec 15 18:41:00 myhostname mattermost[1781247]: github.com/mattermost/mattermost-server/v6/cmd/mattermost/commands.runServer(0xc00025c1c0, 0xc00012a9c0, 0x0, 0x0)
Dec 15 18:41:00 myhostname mattermost[1781247]:         github.com/mattermost/mattermost-server/v6/cmd/mattermost/commands/server.go:100 +0x199 fp=0xc0019c5d48 sp=0xc0019c5c78 pc=0x24e8359
Dec 15 18:41:00 myhostname mattermost[1781247]: github.com/mattermost/mattermost-server/v6/cmd/mattermost/commands.serverCmdF(0x44e2a20, 0x45483f8, 0x0, 0x0, 0x0, 0x0)
Dec 15 18:41:00 myhostname mattermost[1781247]:         github.com/mattermost/mattermost-server/v6/cmd/mattermost/commands/server.go:58 +0x165 fp=0xc0019c5db8 sp=0xc0019c5d48 pc=0x24e80a5
Dec 15 18:41:00 myhostname mattermost[1781247]: github.com/spf13/cobra.(*Command).execute(0x44e2a20, 0xc0001181d0, 0x0, 0x0, 0x44e2a20, 0xc0001181d0)
Dec 15 18:41:00 myhostname mattermost[1781247]:         github.com/spf13/cobra@v1.2.1/command.go:856 +0x472 fp=0xc0019c5e78 sp=0xc0019c5db8 pc=0x24aa2b2
Dec 15 18:41:00 myhostname mattermost[1781247]: github.com/spf13/cobra.(*Command).ExecuteC(0x44e2a20, 0x0, 0xffffffff, 0xc00010e058)
Dec 15 18:41:00 myhostname mattermost[1781247]:         github.com/spf13/cobra@v1.2.1/command.go:974 +0x375 fp=0xc0019c5f58 sp=0xc0019c5e78 pc=0x24aaed5
Dec 15 18:41:00 myhostname mattermost[1781247]: github.com/spf13/cobra.(*Command).Execute(...)
Dec 15 18:41:00 myhostname mattermost[1781247]:         github.com/spf13/cobra@v1.2.1/command.go:902
Dec 15 18:41:00 myhostname mattermost[1781247]: github.com/mattermost/mattermost-server/v6/cmd/mattermost/commands.Run(...)
Dec 15 18:41:00 myhostname mattermost[1781247]:         github.com/mattermost/mattermost-server/v6/cmd/mattermost/commands/root.go:14
Dec 15 18:41:00 myhostname mattermost[1781247]: main.main()
Dec 15 18:41:00 myhostname mattermost[1781247]:         github.com/mattermost/mattermost-server/v6/cmd/mattermost/main.go:31 +0x86 fp=0xc0019c5f88 sp=0xc0019c5f58 pc=0x25d18a6
Dec 15 18:41:00 myhostname mattermost[1781247]: runtime.main()
Dec 15 18:41:00 myhostname mattermost[1781247]:         runtime/proc.go:225 +0x256 fp=0xc0019c5fe0 sp=0xc0019c5f88 pc=0x43c916
Dec 15 18:41:00 myhostname mattermost[1781247]: runtime.goexit()
Dec 15 18:41:00 myhostname mattermost[1781247]:         runtime/asm_amd64.s:1371 +0x1 fp=0xc0019c5fe8 sp=0xc0019c5fe0 pc=0x474701
Dec 15 18:41:00 myhostname mattermost[1781247]: goroutine 2 [force gc (idle)]:
Dec 15 18:41:00 myhostname mattermost[1781247]: runtime.gopark(0x2d68bc8, 0x4511b40, 0x1411, 0x1)
Dec 15 18:41:00 myhostname mattermost[1781247]:         runtime/proc.go:336 +0xe5 fp=0xc000064fb0 sp=0xc000064f90 pc=0x43cd45
Dec 15 18:41:00 myhostname mattermost[1781247]: runtime.goparkunlock(...)
Dec 15 18:41:00 myhostname mattermost[1781247]:         runtime/proc.go:342
Dec 15 18:41:00 myhostname mattermost[1781247]: runtime.forcegchelper()
Dec 15 18:41:00 myhostname mattermost[1781247]:         runtime/proc.go:276 +0xc5 fp=0xc000064fe0 sp=0xc000064fb0 pc=0x43cba5
Dec 15 18:41:00 myhostname mattermost[1781247]: runtime.goexit()
Dec 15 18:41:00 myhostname mattermost[1781247]:         runtime/asm_amd64.s:1371 +0x1 fp=0xc000064fe8 sp=0xc000064fe0 pc=0x474701
Dec 15 18:41:00 myhostname systemd[1]: mattermost.service: Main process exited, code=killed, status=6/ABRT
```

**From a `mattermost.log` perspective:**

```
info  [2021-12-15 18:40:45.728 +01:00] Server is initializing...                     caller="app/server.go:253" go_version=go1.16.7
info  [2021-12-15 18:40:45.729 +01:00] Starting websocket hubs                       caller="app/web_hub.go:93" number_of_hubs=16
info  [2021-12-15 18:40:45.729 +01:00] Pinging SQL                                   caller="sqlstore/store.go:262" database=master
info  [2021-12-15 18:40:45.732 +01:00] Pinging SQL                                   caller="sqlstore/store.go:262" database=migrations
warn  [2021-12-15 18:40:45.878 +01:00] Attempting to upgrade the database schema version caller="sqlstore/upgrade.go:249" stored_version=6.1.0 current_version=6.1.0 new_version=6.2.0
warn  [2021-12-15 18:40:45.910 +01:00] The database schema version has been upgraded caller="sqlstore/upgrade.go:230" version=6.2.0
info  [2021-12-15 18:40:46.051 +01:00] Loaded system translations                    caller="i18n/i18n.go:93" for locale=en from locale=/opt/mattermost/i18n/en.json
info  [2021-12-15 18:40:46.091 +01:00] License key from https://mattermost.com required to unlock enterprise features. caller="app/license.go:90"
info  [2021-12-15 18:40:48.686 +01:00] Current version is 6.2.0 (6.2.0/Mon Dec 13 22:37:51 UTC 2021/7dcc03f1a215faaa5ded6592fb06420a8d87f439/6534470ed63429c42ccf9f2d03305a449abbcde5) caller="app/server.go:581" current_version=6.2.0 build_number=6.2.0 build_date="Mon Dec 13 22:37:51 UTC 2021" build_hash=7dcc03f1a215faaa5ded6592fb06420a8d87f439 build_hash_enterprise=6534470ed63429c42ccf9f2d03305a449abbcde5
info  [2021-12-15 18:40:48.686 +01:00] Enterprise Build                              caller="app/server.go:590" enterprise_build=true
info  [2021-12-15 18:40:48.686 +01:00] Printing current working                      caller="app/server.go:596" directory=/opt/mattermost
info  [2021-12-15 18:40:48.686 +01:00] Loaded config                                 caller="app/server.go:597" source="file:///opt/mattermost/config/config.json"
info  [2021-12-15 18:40:48.853 +01:00] Starting workers                              caller="jobs/workers.go:140"
info  [2021-12-15 18:40:48.854 +01:00] Starting schedulers.                          caller="jobs/schedulers.go:116"
info  [2021-12-15 18:40:48.857 +01:00] License key from https://mattermost.com required to unlock enterprise features. caller="app/license.go:90"
info  [2021-12-15 18:40:48.968 +01:00] Stopping Server...                            caller="app/server.go:998"
info  [2021-12-15 18:40:48.968 +01:00] stopping websocket hub connections            caller="app/web_hub.go:113"
info  [2021-12-15 18:41:00.713 +01:00] Stopped workers                               caller="jobs/workers.go:353"
info  [2021-12-15 18:41:00.714 +01:00] Stopping schedulers.                          caller="jobs/schedulers.go:187"
info  [2021-12-15 18:41:00.714 +01:00] Schedulers stopped.                           caller="jobs/schedulers.go:119"
info  [2021-12-15 18:41:00.715 +01:00] Server stopped                                caller="app/server.go:1084"
```

#### Possible fixes

Unclear

#### Additional information:

* OS: Debian 11 Bullseye (fully patched)
* Postgresql-Version: `13.5-0+deb11u1`
* Mattermost started via `systemd`:

```
root@myhostname:/opt/mattermost/logs# systemctl cat mattermost
# /etc/systemd/system/mattermost.service
[Unit]
Description=Mattermost is an open source, self-hosted Slack-alternative
After=syslog.target network.target postgresql.service
Before=apache2.service

[Service]
Type=simple
User=mattermost
Group=mattermost
ExecStart=/opt/mattermost/bin/mattermost
PrivateTmp=yes
WorkingDirectory=/opt/mattermost

[Install]
WantedBy=multi-user.target
```
* an `strace` of the startup: [strace.log](https://github.com/mattermost/mattermost-server/files/7721847/strace.log)

**Comment by amyblais** [comment]
@agnivade @isacikgoz @streamer45 FYI on this ^

**Comment by amyblais** [comment]
cc @Willyfrog @jfrerich

**Comment by streamer45** [comment]
Problem is that due to this check:

https://github.com/mattermost/mattermost-server/blob/666021e5c87fe4634b54f4b536c45805e0863e8e/app/plugin.go#L177-L181

[`TogglePluginHealthCheckJob()`](https://github.com/mattermost/mattermost-server/blob/666021e5c87fe4634b54f4b536c45805e0863e8e/plugin/environment.go#L509) can indeed receive a `nil` environment and crash. 

@amyblais We should open a ticket and assign to Server Platform (or SET if it's urgent).

**Comment by bc032569e22e7** [comment]
Same here (SIGABRT) on a FreeBSD 13/STABLE /  mariadb 10.4.22, mattermost built with go1.17.5

**Comment by amyblais** [comment]
I opened a ticket for SET: https://mattermost.atlassian.net/browse/MM-40682.

Sounds like this is urgent @jfrerich @Willyfrog @AGMETEOR

**Comment by streamer45** [comment]
By the way, this should only trigger if plugins are disabled in config.

**Comment by bc032569e22e7** [comment]
> By the way, this should only trigger if plugins are disabled in config.

You are right, enabled and running.

**Comment by TwizzyDizzy** [comment]
> By the way, this should only trigger if plugins are disabled in config.

Also confirmed on my end.

Cheers
Thomas

**Comment by Willyfrog** [comment]
@amyblais I'll get SET to work on it, thanks for bringing it to my attention :)

**Comment by agnivade** [comment]
Welp, that's on me. The commit responsible is: https://github.com/mattermost/mattermost-server/commit/83b3090eb967da1076de360ab2330e5e9655b810.

The fix would be to add a `pluginsEnvironment != nil` check inside the if condition again. And also add a test to do an initPlugins  with nil `pluginsEnvironment` and ensure there is no panic.

**Comment by AGMETEOR** [comment]
> Welp, that's on me. The commit responsible is: [83b3090](https://github.com/mattermost/mattermost-server/commit/83b3090eb967da1076de360ab2330e5e9655b810).
> 
> The fix would be to add a `pluginsEnvironment != nil` check inside the if condition again. And also add a test to do an initPlugins with nil `pluginsEnvironment` and ensure there is no panic.

@agnivade should we maintain the `return` inside that if statement

**Comment by agnivade** [comment]
@AGMETEOR - My suggestion was something like this:

```diff
--- a/app/plugin.go
+++ b/app/plugin.go
@@ -176,7 +176,9 @@ func (ch *Channels) initPlugins(c *request.Context, pluginDir, webappPluginDir s
        ch.pluginsLock.RUnlock()
        if pluginsEnvironment != nil || !*ch.srv.Config().PluginSettings.Enable {
                ch.syncPluginsActiveState()
-               pluginsEnvironment.TogglePluginHealthCheckJob(*ch.srv.Config().PluginSettings.EnableHealthCheck)
+               if pluginsEnvironment != nil {
+                       pluginsEnvironment.TogglePluginHealthCheckJob(*ch.srv.Config().PluginSettings.EnableHealthCheck)
+               }
                return
        }

```

**Comment by AGMETEOR** [comment]
@agnivade Thanks for clarification

**Comment by AGMETEOR** [comment]
Fixed here https://github.com/mattermost/mattermost-server/pull/19192
