### ISSUE TITLE
Import from slack failing via `mmctl` and `mattermost import bulk` commands 

### ISSUE THREAD

**Issue by ChimeraFire** [mattermost/mattermost-server#22549]
#### Summary
Import from slack failing via `mmctl` and `mattermost import bulk` commands 

#### Steps to reproduce
Initially encountered in 7.8.1, then also in 7.9.0. First attempted using mmctl import commands listed in [migration guide](https://docs.mattermost.com/onboard/migrating-to-mattermost.html#migrate-from-slack). Then switched to `mattermost import bulk` command to get more details

This is running a bitnami image on Azure: https://docs.bitnami.com/azure/apps/mattermost/
- run an import with the command `sudo -u mattermost bin/mattermost import bulk mattermost_import.jsonl --validate`
- validates fine
- run an import with the command `sudo -u mattermost bin/mattermost import bulk mattermost_import.jsonl --apply`
- error: [invalid memory address or nil pointer dereference](panic: runtime error: invalid memory address or nil pointer dereference) at import_functions.go:1478

jsonl contents:
```jsonl
{"type":"version","version":1}
{"type":"channel","channel":{"team":"Default","name":"authoring","display_name":"authoring","type":"O","header":"","purpose":""}}
{"type":"user","user":{"username":"-----","email":"------@------.com","auth_service":null,"nickname":"","first_name":"","last_name":"","position":"","roles":"system_user","locale":null,"teams":[{"name":"Default","roles":"team_user","channels":[{"name":"authoring","roles":"channel_user"}]}]}}
{"type":"post","post":{"team":"Default","channel":"authoring","user":"------","type":null,"message":"But.. I did it just for pointerup, tested with no joy, went back and replaced all of them, and now I'm getting pointerdown and pointerup both for the caret","props":null,"create_at":1632174749049,"edit_at":null,"replies":[],"attachments":[]}}
```

#### Expected behavior
Should just work!

#### Observed behavior (that appears unintentional) 
```
Running Bulk Import. This may take a long time.

{"timestamp":"2023-03-16 22:01:08.107 Z","level":"info","msg":"Starting workers for new segment","caller":"app/import.go:259","old_segment":"version","new_segment":"channel","workers":2}
{"timestamp":"2023-03-16 22:01:08.107 Z","level":"info","msg":"Finished parsing segment, waiting for workers to finish","caller":"app/import.go:240","old_segment":"channel","new_segment":"user"}
{"timestamp":"2023-03-16 22:01:08.107 Z","level":"info","msg":"Started new bulk import worker","caller":"app/import.go:118","bulk_import_worker_id":"5wxbdemg6tyounftmhoaiehz5h"}
{"timestamp":"2023-03-16 22:01:08.107 Z","level":"info","msg":"Validating channel","caller":"app/import_functions.go:258","channel_name":"authoring"}
{"timestamp":"2023-03-16 22:01:08.107 Z","level":"info","msg":"Importing channel","caller":"app/import_functions.go:269","channel_name":"authoring"}
{"timestamp":"2023-03-16 22:01:08.107 Z","level":"info","msg":"Started new bulk import worker","caller":"app/import.go:118","bulk_import_worker_id":"ekefsbo5ni8wux9xrg4yodtxbc"}
{"timestamp":"2023-03-16 22:01:08.107 Z","level":"info","msg":"Bulk import worker finished","caller":"app/import.go:121","bulk_import_worker_id":"ekefsbo5ni8wux9xrg4yodtxbc","processed_lines":0}
{"timestamp":"2023-03-16 22:01:08.120 Z","level":"info","msg":"Bulk import worker finished","caller":"app/import.go:121","bulk_import_worker_id":"5wxbdemg6tyounftmhoaiehz5h","processed_lines":1}
{"timestamp":"2023-03-16 22:01:08.120 Z","level":"info","msg":"Starting workers for new segment","caller":"app/import.go:259","old_segment":"channel","new_segment":"user","workers":2}
{"timestamp":"2023-03-16 22:01:08.120 Z","level":"info","msg":"Finished parsing segment, waiting for workers to finish","caller":"app/import.go:240","old_segment":"user","new_segment":"post"}
{"timestamp":"2023-03-16 22:01:08.120 Z","level":"info","msg":"Started new bulk import worker","caller":"app/import.go:118","bulk_import_worker_id":"4pk1js6hgbbwtx4ukhixdss1ow"}
{"timestamp":"2023-03-16 22:01:08.120 Z","level":"info","msg":"Validating user","caller":"app/import_functions.go:331","user_name":"dannya"}
{"timestamp":"2023-03-16 22:01:08.120 Z","level":"info","msg":"Importing user","caller":"app/import_functions.go:342","user_name":"dannya"}
{"timestamp":"2023-03-16 22:01:08.120 Z","level":"info","msg":"Started new bulk import worker","caller":"app/import.go:118","bulk_import_worker_id":"7d4g3it8gbnntrjy35n73w94te"}
{"timestamp":"2023-03-16 22:01:08.120 Z","level":"info","msg":"Bulk import worker finished","caller":"app/import.go:121","bulk_import_worker_id":"7d4g3it8gbnntrjy35n73w94te","processed_lines":0}
{"timestamp":"2023-03-16 22:01:08.211 Z","level":"info","msg":"Post.Message has size restrictions","caller":"sqlstore/post_store.go:2544","max_characters":16383,"max_bytes":65535}
{"timestamp":"2023-03-16 22:01:08.323 Z","level":"info","msg":"Bulk import worker finished","caller":"app/import.go:121","bulk_import_worker_id":"4pk1js6hgbbwtx4ukhixdss1ow","processed_lines":1}
{"timestamp":"2023-03-16 22:01:08.323 Z","level":"info","msg":"Starting workers for new segment","caller":"app/import.go:259","old_segment":"user","new_segment":"post","workers":2}
{"timestamp":"2023-03-16 22:01:08.323 Z","level":"info","msg":"Started new bulk import worker","caller":"app/import.go:118","bulk_import_worker_id":"6xijy86m7j84fcnjujwm4qotdy"}
{"timestamp":"2023-03-16 22:01:08.323 Z","level":"info","msg":"Validating post lines","caller":"app/import_functions.go:1422","count":1,"first_line":4}
{"timestamp":"2023-03-16 22:01:08.323 Z","level":"info","msg":"Importing post lines","caller":"app/import_functions.go:1435","count":1,"first_line":4}
{"timestamp":"2023-03-16 22:01:08.323 Z","level":"info","msg":"Started new bulk import worker","caller":"app/import.go:118","bulk_import_worker_id":"pgfcyw35ftrdikrcb5cs81u7dy"}
{"timestamp":"2023-03-16 22:01:08.323 Z","level":"info","msg":"Bulk import worker finished","caller":"app/import.go:121","bulk_import_worker_id":"pgfcyw35ftrdikrcb5cs81u7dy","processed_lines":0}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d2db48]

goroutine 6198 [running]:
github.com/mattermost/mattermost-server/v6/app.(*App).importMultiplePostLines(0xc001391860, {0x2fc43c0, 0xc001976000}, {0xc000b5c460, 0x1, 0x1?}, 0x0)
        github.com/mattermost/mattermost-server/v6/app/import_functions.go:1478 +0xda8
github.com/mattermost/mattermost-server/v6/app.(*App).bulkImportWorker(0xc001767fd0?, {0x2fc43c0, 0xc001976000}, 0xf8?, 0xc00015a120, 0x0?, 0x0?)
        github.com/mattermost/mattermost-server/v6/app/import.go:163 +0xc7c
created by github.com/mattermost/mattermost-server/v6/app.(*App).bulkImport
        github.com/mattermost/mattermost-server/v6/app/import.go:271 +0x131a
```

#### Possible fixes
https://github.com/mattermost/mattermost-server/blob/master/app/import_functions.go#L1478

**Comment by amyblais** [comment]
Thanks, opened https://mattermost.atlassian.net/browse/MM-51487.

**Comment by agnivade** [comment]
@ChimeraFire - With the .jsonl file that you pasted, I am getting the following. Can you please re-confirm the input contents?

```
Running Bulk Import. This may take a long time.

info  [2023-03-20 13:22:43.877 +05:30] Starting workers for new segment              caller="app/import.go:259" old_segment=version new_segment=channel workers=2
info  [2023-03-20 13:22:43.877 +05:30] Finished parsing segment, waiting for workers to finish caller="app/import.go:240" old_segment=channel new_segment=user
info  [2023-03-20 13:22:43.877 +05:30] Started new bulk import worker                caller="app/import.go:118" bulk_import_worker_id=gi9bxmihj7deurmjtj8opb917e
info  [2023-03-20 13:22:43.877 +05:30] Started new bulk import worker                caller="app/import.go:118" bulk_import_worker_id=qr5cm6tc3fgwfda79rojeab4wy
info  [2023-03-20 13:22:43.877 +05:30] Bulk import worker finished                   caller="app/import.go:121" bulk_import_worker_id=qr5cm6tc3fgwfda79rojeab4wy processed_lines=0
info  [2023-03-20 13:22:43.877 +05:30] Validating channel                            caller="app/import_functions.go:258" channel_name=authoring
info  [2023-03-20 13:22:43.877 +05:30] Importing channel                             caller="app/import_functions.go:269" channel_name=authoring
info  [2023-03-20 13:22:43.878 +05:30] Bulk import worker finished                   caller="app/import.go:121" bulk_import_worker_id=gi9bxmihj7deurmjtj8opb917e processed_lines=1
BulkImport: Error importing channel. Team with name "Default" could not be found., resource: Team id: name=Default
Error occurred on data file line 2
info  [2023-03-20 13:22:43.878 +05:30] Stopping Server...                            caller="app/server.go:666"
info  [2023-03-20 13:22:43.878 +05:30] Shutting down plugins                         caller="app/plugin.go:379"
debug [2023-03-20 13:22:43.878 +05:30] Disabling plugin health check job             caller="plugin/environment.go:622"
info  [2023-03-20 13:22:43.880 +05:30] plugin process exited                         caller="plugin/hclog_adapter.go:61" plugin_id=playbooks wrapped_extras=pathplugins/playbooks/server/dist/plugin-linux-amd64pid991167
debug [2023-03-20 13:22:43.880 +05:30] plugin exited                                 caller="plugin/hclog_adapter.go:54" plugin_id=playbooks
info  [2023-03-20 13:22:43.880 +05:30] stopping websocket hub connections            caller="platform/web_hub.go:115"
info  [2023-03-20 13:22:43.880 +05:30] Server stopped                                caller="app/server.go:748"
Error: BulkImport: Error importing channel. Team with name "Default" could not be found., resource: Team id: name=Default
```

**Comment by agnivade** [comment]
@ChimeraFire - I had to change to a lower case team name since upper case team names aren't allowed. After changing to `default`, and with an input file of

```
{"type":"version","version":1}
{"type":"channel","channel":{"team":"default","name":"authoring","display_name":"authoring","type":"O","header":"","purpose":""}}
{"type":"user","user":{"username":"test12","email":"test12@example.com","auth_service":null,"nickname":"","first_name":"","last_name":"","position":"","roles":"system_user","locale":null,"teams":[{"name":"default","roles":"team_user","channels":[{"name":"authoring","roles":"channel_user"}]}]}}
{"type":"post","post":{"team":"default","channel":"authoring","user":"test12","type":null,"message":"But.. I did it just for pointerup, tested with no joy, went back and replaced all of them, and now I'm getting pointerdown and pointerup both for the caret","props":null,"create_at":1632174749049,"edit_at":null,"replies":[],"attachments":[]}}
```

it seems to work:

```
Running Bulk Import. This may take a long time.

info  [2023-03-21 10:30:47.616 +05:30] Starting workers for new segment              caller="app/import.go:259" old_segment=version new_segment=channel workers=2
info  [2023-03-21 10:30:47.616 +05:30] Finished parsing segment, waiting for workers to finish caller="app/import.go:240" old_segment=channel new_segment=user
info  [2023-03-21 10:30:47.616 +05:30] Started new bulk import worker                caller="app/import.go:118" bulk_import_worker_id=i13pmpttofb3byy9yoomdqunaa
info  [2023-03-21 10:30:47.616 +05:30] Validating channel                            caller="app/import_functions.go:258" channel_name=authoring
info  [2023-03-21 10:30:47.616 +05:30] Importing channel                             caller="app/import_functions.go:269" channel_name=authoring
info  [2023-03-21 10:30:47.616 +05:30] Started new bulk import worker                caller="app/import.go:118" bulk_import_worker_id=zn8dp3sitbbm3qun6opnptnbeo
info  [2023-03-21 10:30:47.616 +05:30] Bulk import worker finished                   caller="app/import.go:121" bulk_import_worker_id=zn8dp3sitbbm3qun6opnptnbeo processed_lines=0
info  [2023-03-21 10:30:47.621 +05:30] Bulk import worker finished                   caller="app/import.go:121" bulk_import_worker_id=i13pmpttofb3byy9yoomdqunaa processed_lines=1
info  [2023-03-21 10:30:47.621 +05:30] Starting workers for new segment              caller="app/import.go:259" old_segment=channel new_segment=user workers=2
info  [2023-03-21 10:30:47.621 +05:30] Finished parsing segment, waiting for workers to finish caller="app/import.go:240" old_segment=user new_segment=post
info  [2023-03-21 10:30:47.621 +05:30] Started new bulk import worker                caller="app/import.go:118" bulk_import_worker_id=c3yo93m9tjb67nbezkcng1e1so
info  [2023-03-21 10:30:47.621 +05:30] Validating user                               caller="app/import_functions.go:331" user_name=test12
info  [2023-03-21 10:30:47.621 +05:30] Importing user                                caller="app/import_functions.go:342" user_name=test12
info  [2023-03-21 10:30:47.621 +05:30] Started new bulk import worker                caller="app/import.go:118" bulk_import_worker_id=mrps4q3catge8jrz4ybgc4uy5w
info  [2023-03-21 10:30:47.621 +05:30] Bulk import worker finished                   caller="app/import.go:121" bulk_import_worker_id=mrps4q3catge8jrz4ybgc4uy5w processed_lines=0
info  [2023-03-21 10:30:47.689 +05:30] Post.Message has size restrictions            caller="sqlstore/post_store.go:2544" max_characters=16383 max_bytes=65535
info  [2023-03-21 10:30:47.960 +05:30] Bulk import worker finished                   caller="app/import.go:121" bulk_import_worker_id=c3yo93m9tjb67nbezkcng1e1so processed_lines=1
info  [2023-03-21 10:30:47.960 +05:30] Starting workers for new segment              caller="app/import.go:259" old_segment=user new_segment=post workers=2
info  [2023-03-21 10:30:47.960 +05:30] Started new bulk import worker                caller="app/import.go:118" bulk_import_worker_id=971mmad5bi8qzjd5zi3j9h54mo
info  [2023-03-21 10:30:47.960 +05:30] Validating post lines                         caller="app/import_functions.go:1422" count=1 first_line=4
info  [2023-03-21 10:30:47.960 +05:30] Importing post lines                          caller="app/import_functions.go:1435" count=1 first_line=4
info  [2023-03-21 10:30:47.960 +05:30] Started new bulk import worker                caller="app/import.go:118" bulk_import_worker_id=oq79eegjxirh7ynrxixidopm7e
info  [2023-03-21 10:30:47.960 +05:30] Bulk import worker finished                   caller="app/import.go:121" bulk_import_worker_id=oq79eegjxirh7ynrxixidopm7e processed_lines=0
info  [2023-03-21 10:30:47.971 +05:30] Bulk import worker finished                   caller="app/import.go:121" bulk_import_worker_id=971mmad5bi8qzjd5zi3j9h54mo processed_lines=1
Finished Bulk Import.
info  [2023-03-21 10:30:47.972 +05:30] Stopping Server...                            caller="app/server.go:669"
info  [2023-03-21 10:30:47.972 +05:30] Shutting down Email batching service...       caller="email/service.go:85"
info  [2023-03-21 10:30:47.972 +05:30] Shutting down plugins                         caller="app/plugin.go:379"
debug [2023-03-21 10:30:47.972 +05:30] Disabling plugin health check job             caller="plugin/environment.go:622"
info  [2023-03-21 10:30:47.976 +05:30] plugin process exited                         caller="plugin/hclog_adapter.go:61" plugin_id=playbooks wrapped_extras=pathplugins/playbooks/server/dist/plugin-linux-amd64pid2132850
debug [2023-03-21 10:30:47.976 +05:30] plugin exited                                 caller="plugin/hclog_adapter.go:54" plugin_id=playbooks
info  [2023-03-21 10:30:47.976 +05:30] stopping websocket hub connections            caller="platform/web_hub.go:115"
info  [2023-03-21 10:30:47.976 +05:30] Server stopped                                caller="app/server.go:755"
```

**Comment by ChimeraFire** [comment]
Thank you so much for your attention to this. I can confirm that the import now works on my end as well.

I must've somehow missed the lowercase restriction in the documentation. It would be nice if the importer or validator could give a more informative error.

**Comment by agnivade** [comment]
Or we could just lowercase the team name automatically. I'll update the ticket accordingly. Thanks.

**Comment by agnivade** [comment]
Ticket updated: https://mattermost.atlassian.net/browse/MM-51487. Closing this. Thanks!
