### ISSUE TITLE
Import error for trello json export 

### ISSUE THREAD

**Issue by teknightstick** [mattermost/mattermost-server#23052]
## Steps to reproduce the behavior

1. Go to ...

https://docs.mattermost.com/boards/migrate-to-boards.html#import-from-trello

2. Select  ...

npx ts-node importTrello.ts -i "C:\Users\bulle\Downloads\trelloboard1stattempt.json" -o archive.boardarchive

3. Scroll down to ...

npx ts-node importTrello.ts -i "C:\Users\bulle\Downloads\trelloboard1stattempt.json" -o archive.boardarchive
C:\Users\bulle\AppData\Local\npm-cache\_npx\1bf7c3c15bf47d04\node_modules\ts-node\src\index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
importTrello.ts:3:21 - error TS2307: Cannot find module 'fs' or its corresponding type declarations.

3 import * as fs from 'fs'
                      ~~~~
importTrello.ts:4:22 - error TS2307: Cannot find module 'minimist' or its corresponding type declarations.

4 import minimist from 'minimist'
                       ~~~~~~~~~~
importTrello.ts:5:20 - error TS2307: Cannot find module 'process' or its corresponding type declarations.

5 import {exit} from 'process'
                     ~~~~~~~~~
importTrello.ts:18:2 - error TS2304: Cannot find name 'global'.

18 (global.window as any) = {}
    ~~~~~~
importTrello.ts:35:48 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

35     const args: minimist.ParsedArgs = minimist(process.argv.slice(2))
                                                  ~~~~~~~

    at createTSError (C:\Users\bulle\AppData\Local\npm-cache\_npx\1bf7c3c15bf47d04\node_modules\ts-node\src\index.ts:859:12)
    at reportTSError (C:\Users\bulle\AppData\Local\npm-cache\_npx\1bf7c3c15bf47d04\node_modules\ts-node\src\index.ts:863:19)
    at getOutput (C:\Users\bulle\AppData\Local\npm-cache\_npx\1bf7c3c15bf47d04\node_modules\ts-node\src\index.ts:1077:36)
    at Object.compile (C:\Users\bulle\AppData\Local\npm-cache\_npx\1bf7c3c15bf47d04\node_modules\ts-node\src\index.ts:1433:41)
    at Module.m._compile (C:\Users\bulle\AppData\Local\npm-cache\_npx\1bf7c3c15bf47d04\node_modules\ts-node\src\index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\bulle\AppData\Local\npm-cache\_npx\1bf7c3c15bf47d04\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {        
  diagnosticCodes: [ 2307, 2307, 2307, 2304, 2580 ]
}

C:\Ai\dgx\LiquidAcre\focalboard\import\trello>

## Expected behavior

Exported trello board named archive.boardarchive

A clear and concise description of what you expected to happen.

## Screenshots (optional)

If applicable, add screenshots or a screen recording to elaborate on the problem.

## Edition and Platform

 - Edition: Win10 main branch
 - Version: [e.g. v0.15.0]
 - Browser and OS: vs code
 
## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by gladipero** [comment]
@wuwinson @teknightstick I was able to replicate the issue if the step to install npm **again** from the inside of the import/trello folder is not executed. I ran the commands following the latest docs(https://docs.mattermost.com/boards/migrate-to-boards.html#import-from-trello), which worked like a charm for me.
