### ISSUE TITLE
The File Download Prompt Repeatedly Appears

### ISSUE THREAD

**Issue by creidPMteldio** [mattermost/mattermost-server#23379]
#### Summary
When I download a file from Mattermost, on my Windows 11 laptop, the "Save As" dialog appears, I save the file, and then - until I forcefully quite Mattermost - the "Save As" dialog repeatedly appears, regardless of how many times I hit the "Cancel" button.

#### Steps to reproduce

- I'm running Windows 11 22H2, build 22624.1755
- I'm running Mattermost v5.3.1, commit 2c3

1. Within a stream chat, click to download a file that someone has posted. 
2. When the "Save As" dialog appears, save the file in the desired location (in my case, I was saving it to my Downloads folder)

#### Expected behavior
The file will be correctly saved, and no further "Save As" dialog boxes will appear.

#### Observed behavior (that appears unintentional) 
The file is successfully saved, but then multiple "Save As" dialogs appear - it's like Mattermost is stuck in a loop, auto-generating the prompts.

In Mattermost's main.txt, I can see repeated errors that look like this (the "<redcated>" entries are mine):

[2023-05-11 14:19:39.547] [info]  [Teldio___TAB_MESS...] failed loading https://chat.<redacted>.com/user_uploads/2/65/QrTTmizcbhr-tpsfyv8KISai/<redacted>.json: Error: ERR_FAILED (-2) loading 'https://chat.<redcated>.com/user_uploads/2/65/QrTTmizcbhr-tpsfyv8KISai/<redcated>.json', retrying in 5 seconds
[2023-05-11 14:19:44.673] [info]  [Teldio___TAB_MESS...] failed loading https://chat.<redacted>.com/user_uploads/2/65/QrTTmizcbhr-tpsfyv8KISai/<redacted>.json: Error: ERR_FAILED (-2) loading 'https://chat.<redcated>.com/user_uploads/2/65/QrTTmizcbhr-tpsfyv8KISai/<redcated>.json', retrying in 5 seconds
[2023-05-11 14:19:49.693] [info]  [Teldio___TAB_MESS...] failed loading https://chat.<redacted>.com/user_uploads/2/65/QrTTmizcbhr-tpsfyv8KISai/<redacted>.json: Error: ERR_FAILED (-2) loading 'https://chat.<redcated>.com/user_uploads/2/65/QrTTmizcbhr-tpsfyv8KISai/<redcated>.json', retrying in 5 seconds
[2023-05-11 14:19:54.727] [info]  [Teldio___TAB_MESS...] failed loading https://chat.<redacted>.com/user_uploads/2/65/QrTTmizcbhr-tpsfyv8KISai/<redacted>.json: Error: ERR_FAILED (-2) loading 'https://chat.<redcated>.com/user_uploads/2/65/QrTTmizcbhr-tpsfyv8KISai/<redcated>.json', retrying in 5 seconds
[2023-05-11 14:19:59.748] [error] [Teldio___TAB_MESSAGING] failed to load deeplink https://chat.<redcated>.com/user_uploads/2/65/QrTTmizcbhr-tpsfyv8KISai/<redcated>.json: Error: ERR_FAILED (-2) loading 'https://chat.<redcated>.com/user_uploads/2/65/QrTTmizcbhr-tpsfyv8KISai/<redcated>.json'
[2023-05-11 14:19:59.749] [info]  [Teldio___TAB_MESS...] Couldn't stablish a connection with https://chat.redcated.com/user_uploads/2/65/QrTTmizcbhr-tpsfyv8KISai/<redcated>.json: Error: ERR_FAILED (-2) loading 'https://chat.<redacted>.com/user_uploads/2/65/QrTTmizcbhr-tpsfyv8KISai/<redacted<.json'. Will continue to retry in the background.
[2023-05-11 14:20:28.476] [warn]  main window closed
[2023-05-11 14:20:33.178] [debug] DownloadsManager.init {
  'this.json': {
    '<redcated>.log': {
      addedAt: 1682018004626,
      filename: '<redcated>-error.log',
      mimeType: 'application/octet-stream',
      location: 'C:\\Users\\cwrei\\Downloads\\<redcated>.log',
      progress: 100,
      receivedBytes: 3837,
      state: 'completed',
      totalBytes: 3837,
      type: 'file'
    },
    '<redcated>.saz': {
      addedAt: 1682614944599,
      filename: '<redcated>.saz',
      mimeType: 'application/octet-stream',
      location: 'C:\\Users\\cwrei\\Downloads\\<redcated>.saz',
      progress: 100,
      receivedBytes: 39498,
      state: 'completed',
      totalBytes: 39498,
      type: 'file'
    },
    '<redcated>.json': {
      addedAt: 1683829184356,
      filename: '<redcated>.json',
      mimeType: 'application/json',
      location: 'C:\\Users\\cwrei\\Downloads\\<redcated>.json',
      progress: 100,
      receivedBytes: 387,
      state: 'completed',
      totalBytes: 387,
      type: 'file'
    }
  },
  validatedJSON: {
    '<redcated>-error.log': {
      addedAt: 1682018004626,
      filename: '<redcated>-error.log',
      mimeType: 'application/octet-stream',
      location: 'C:\\Users\\cwrei\\Downloads\\<redcated>-error.log',
      progress: 100,
      receivedBytes: 3837,
      state: 'completed',
      totalBytes: 3837,
      type: 'file'
    },
    '<redcated>.saz': {
      addedAt: 1682614944599,
      filename: '<redcated>-create.saz',
      mimeType: 'application/octet-stream',
      location: 'C:\\Users\\cwrei\\Downloads\\<redcated>-create.saz',
      progress: 100,
      receivedBytes: 39498,
      state: 'completed',
      totalBytes: 39498,
      type: 'file'
    },
    '<redcated>.json': {
      addedAt: 1683829184356,
      filename: '<redcated>.json',
      mimeType: 'application/json',
      location: 'C:\\Users\\cwrei\\Downloads\\<redcated>.json',
      progress: 100,
      receivedBytes: 387,
      state: 'completed',
      totalBytes: 387,
      type: 'file'
    }
  }
}

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
@creidPMteldio Do you also reproduce this on webapp? What Mattermost server version are you on? 

You can find your server version via Main Menu > About (see screenshot):
<img width="282" alt="Screenshot at May 10 10-38-59" src="https://github.com/mattermost/mattermost-server/assets/29708087/9a0cb780-3a37-435b-925c-6d13743a2e9b">

**Comment by creidPMteldio** [comment]
Ah - I can see it in the web app.

We are running Zulip server v6.1.

**Comment by amyblais** [comment]
@creidPMteldio Thank you, v6.1 is currently an unsupported server version. Would you be open to asking your admin to upgrade your server to the latest version? Or would you be open to testing if you reproduce the issue at https://community.mattermost.com/ which is on the latest version?

**Comment by creidPMteldio** [comment]
Ah - I didn't realize it was unsupported. I thought it was just one minor version behind.

Ya - upgrading to v6.2 isn't a problem. I'll get the admin to do that, and then get back to you with the results!

**Comment by amyblais** [comment]
Thank you - actually our most recent server version is v7.10 https://docs.mattermost.com/upgrade/release-lifecycle.html.

**Comment by amyblais** [comment]
No, I don't think we maintain Zulip.

@devinbinnie Do the log errors in the original post indicate an issue, or have you seen this issue before? The reporter is able to reproduce this on desktop app but not on webapp.

**Comment by devinbinnie** [comment]
Nothing in the original logs indicate an issue. @creidPMteldio If you turn on debug logging in the Settings window, do you get additional logs when you're trying to do a Save As?

**Comment by creidPMteldio** [comment]
Checking now......hold tight.....  =)

**Comment by creidPMteldio** [comment]
Interesting! I'm seeing (in the midst of a bunch of really verbose logs, obvs) this error:

[2023-05-29 09:53:47.188] [verbose] There was an error accessing the registry for {
  hive: 'HKLM',
  key: '\\Software\\Policies\\Mattermost\\DefaultServerList',
  utf8: true
} ProcessUncleanExitError: QUERY command exited with code 1:

ERROR: The system was unable to find the specified registry key or value.
    at mkErrorMsg (C:\Users\cwrei\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:44109:10)
    at ChildProcess.<anonymous> (C:\Users\cwrei\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:44509:10)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:313:12)
[2023-05-29 09:53:47.190] [verbose] Trying without UTF-8... {
  hive: 'HKLM',
  key: '\\Software\\Policies\\Mattermost\\DefaultServerList'
}

**Comment by devinbinnie** [comment]
> Interesting! I'm seeing (in the midst of a bunch of really verbose logs, obvs) this error:
> 
> [2023-05-29 09:53:47.188] [verbose] There was an error accessing the registry for { hive: 'HKLM', key: '\Software\Policies\Mattermost\DefaultServerList', utf8: true } ProcessUncleanExitError: QUERY command exited with code 1:
> 
> ERROR: The system was unable to find the specified registry key or value. at mkErrorMsg (C:\Users\cwrei\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:44109:10) at ChildProcess. (C:\Users\cwrei\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:44509:10) at ChildProcess.emit (node:events:513:28) at maybeClose (node:internal/child_process:1091:16) at Socket. (node:internal/child_process:449:11) at Socket.emit (node:events:513:28) at Pipe. (node:net:313:12) [2023-05-29 09:53:47.190] [verbose] Trying without UTF-8... { hive: 'HKLM', key: '\Software\Policies\Mattermost\DefaultServerList' }

These are unrelated, they have to do with reading the registry for pre-configured servers.

**Comment by creidPMteldio** [comment]
Ah - OK. Sorry about that.

Here's what is likely more relevant logging:

[2023-05-29 09:46:00.366] [debug] DownloadsDropdownView.updateDownloadsDropdown
[2023-05-29 09:46:00.366] [debug] DownloadsDropdownMenuView.handleClose
[2023-05-29 09:46:00.367] [debug] DownloadsDropdownView.updateDownloadsDropdownMenuItem {}
[2023-05-29 09:46:00.368] [debug] DownloadsDropdownView.updateDownloadsDropdown
[2023-05-29 09:46:01.146] [debug] webContentEvents.did-start-navigation {
  webContentsId: 5,
  url: 'https://chat.<something>.com/user_uploads/2/f2/ReGe8_TCFquQOAH7UyIXH3yf/<something>-tenant-search-user-response.json'
}
[2023-05-29 09:46:01.150] [info]  [Teldio___TAB_MESS...] failed loading https://chat.<something>.com/user_uploads/2/f2/ReGe8_TCFquQOAH7UyIXH3yf/<something>-tenant-search-user-response.json: Error: ERR_FAILED (-2) loading 'https://chat.<something>.com/user_uploads/2/f2/ReGe8_TCFquQOAH7UyIXH3yf/<something>-tenant-search-user-response.json', retrying in 5 seconds
[2023-05-29 09:46:01.152] [debug] DownloadsManager.handleNewDownload {
  item: {
    pause: '[function] function pause() { [native code] }',
    isPaused: '[function] function isPaused() { [native code] }',
    resume: '[function] function resume() { [native code] }',
    canResume: '[function] function canResume() { [native code] }',
    cancel: '[function] function cancel() { [native code] }',
    getReceivedBytes: '[function] function getReceivedBytes() { [native code] }',
    getTotalBytes: '[function] function getTotalBytes() { [native code] }',
    getMimeType: '[function] function getMimeType() { [native code] }',
    hasUserGesture: '[function] function hasUserGesture() { [native code] }',
    getFilename: '[function] function getFilename() { [native code] }',
    getContentDisposition: '[function] function getContentDisposition() { [native code] }',
    getURL: '[function] function getURL() { [native code] }',
    getURLChain: '[function] function getURLChain() { [native code] }',
    getState: '[function] function getState() { [native code] }',
    isDone: '[function] function isDone() { [native code] }',
    setSavePath: '[function] function setSavePath() { [native code] }',
    getSavePath: '[function] function getSavePath() { [native code] }',
    savePath: '',
    setSaveDialogOptions: '[function] function setSaveDialogOptions() { [native code] }',
    getSaveDialogOptions: '[function] function getSaveDialogOptions() { [native code] }',
    getLastModifiedTime: '[function] function getLastModifiedTime() { [native code] }',
    getETag: '[function] function getETag() { [native code] }',
    getStartTime: '[function] function getStartTime() { [native code] }'
  },
  sourceURL: 'https://chat.<something>.com/#narrow/stream/5-dev/topic/<something>.20Notification.20Issue'
}
[2023-05-29 09:46:01.153] [debug] DownloadsManager.shouldShowSaveDialog { downloadLocation: 'C:\\Users\\cwrei\\Downloads' }
[2023-05-29 09:46:05.424] [debug] App.handleAppBeforeQuit
[2023-05-29 09:46:05.425] [debug] Utils.flushCookiesStore
[2023-05-29 09:46:05.426] [debug] MainWindow.on.close
[2023-05-29 09:46:05.482] [warn]  main window closed

**Comment by creidPMteldio** [comment]
Sorry - I put in placeholder text, and it is markup. My bad!

There is a legit URL there.  =)  chat.something.com

**Comment by devinbinnie** [comment]
Gotcha, thanks. If you're using the Mattermost Desktop App to access a Zulip server, that's likely why you're seeing this strange behaviour, because our app is designed in a way to make sure that downloads function correctly. I'm guessing Zulip either tries to open a new tab or something like that.

**Comment by creidPMteldio** [comment]
OK! I'll get my admin to upgrade the server first, and see if that helps. If it doesn't, I'll figure out something else do to, like using a different app.

Thanks for your help here guys!
