### ISSUE TITLE
If Mattermost database is located on MySQL database cluster created by mysql-operator, database cluster fails to restart

### ISSUE THREAD

**Issue by cerebrate** [mattermost/mattermost-server#23392]
#### Summary
If Mattermost database is located on MySQL database cluster created by mysql-operator, database cluster fails to restart

#### Steps to reproduce

1. Take a single-node Kubernetes cluster,
2. Install mysql-operator on the cluster using the Helm chart
3. Install mattermost-operator on the cluster using the Helm chart
4. Create a simple InnoDBCluster for Mattermost using the following definition:

```
---
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mattermostdb
  namespace: mattermost
spec:
  secretName: mattermostdb-pwd
  instances: 1
  router:
    instances: 1
  datadirVolumeClaimTemplate:
    storageClassName: ""
    volumeName: mattermostdb-pv
    accessModes:
      - ReadWriteOnce
  tlsUseSelfSigned: true
```

(creating an appropriate private volume and database secret beforehand)

5. Create a Mattermost installation using the following definition

```
---
apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mattermost
  namespace: mattermost
spec:
  version: 7.9.2
  size: 100users
  database:
    external:
      secret: mattermost-db-credentials
```

(creating appropriate external file store, database secret, and ingress beforehand)

6. Log on to and configure the resulting Mattermost instance, including the Boards plugin
7. Reboot the node.

#### Expected behavior

I would expect in this case that the database and Mattermost pods would all restart successfully post-reboot and the Mattermost instance would be accessible and functional.

#### Observed behavior (that appears unintentional) 

The Mattermost instance is inaccessible after reboot. Further examination shows that neither the Mattermost pod nor the router pod for the MySQL database cluster have been able to start. Examination of the logs of the mysql-operator pod finds the following error:

```
2023-05-15 23:31:13: Info: Validating InnoDB page size of instance 'mattermostdb-0.mattermostdb-instances.mattermost.svc.cluster.local:3306'.
2023-05-15 23:31:13: Info: Checking if performance_schema is enabled on instance 'mattermostdb-0.mattermostdb-instances.mattermost.svc.cluster.local:3306'.
2023-05-15 23:31:13: Info: Validating configuration of mattermostdb-0.mattermostdb-instances.mattermost.svc.cluster.local:3306 (mycnf = )

ERROR: Instance must be configured and validated with dba.check_instance_configuration() and dba.configure_instance() before it can be used in an InnoDB cluster.
2023-05-15 23:31:13: Error: Instance must be configured and validated with dba.check_instance_configuration() and dba.configure_instance() before it can be used in an InnoDB cluster.
[2023-05-15 23:31:13,865] kopf.objects         [ERROR   ] Handler 'on_pod_create' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/lib/mysqlsh/python-packages/kopf/_core/actions/execution.py", line 279, in execute_handler_once
    result = await invoke_handler(
  File "/usr/lib/mysqlsh/python-packages/kopf/_core/actions/execution.py", line 374, in invoke_handler
    result = await invocation.invoke(
  File "/usr/lib/mysqlsh/python-packages/kopf/_core/actions/invocation.py", line 139, in invoke
    await asyncio.shield(future)  # slightly expensive: creates tasks
  File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/mysqlsh/python-packages/mysqloperator/controller/innodbcluster/operator_cluster.py", line 542, in on_pod_create
    cluster_ctl.on_pod_created(pod, logger)
  File "/usr/lib/mysqlsh/python-packages/mysqloperator/controller/innodbcluster/cluster_controller.py", line 699, in on_pod_created
    shellutils.RetryLoop(logger).call(self.create_cluster, pod, logger)
  File "/usr/lib/mysqlsh/python-packages/mysqloperator/controller/shellutils.py", line 93, in call
    return f(*args)
  File "/usr/lib/mysqlsh/python-packages/mysqloperator/controller/innodbcluster/cluster_controller.py", line 273, in create_cluster
    self.dba_cluster = dba.create_cluster(
RuntimeError: Dba.create_cluster: Instance check failed

```

#### Possible fixes

Needing to get the system back up and running rapidly, I elected to back up the database and attempt a manual patch. Using `dba.checkInstanceConfiguration()` in the database instance produced a report indicating that the `mattermost.focalboard_file_info` table did not have a primary key or equivalent column, a requirement for Group Replication, itself a requirement for running even a single-instance MySQL database using the MySQL Operator.

Running the following commands in the MySQL client attached to the database instance in question:

```
USE mattermost;
ALTER TABLE focalboard_file_info ADD COLUMN mysql_fix INT NOT NULL INVISIBLE AUTO_INCREMENT UNIQUE KEY;
```

followed by, in the MySQL shell attached likewise:

```
dba.checkInstanceConfiguration()
```

restored normal operation, allowing the database router and Mattermost pods to come up. After this, Mattermost (and Boards) appear to be operating normally.

I suggest the easiest fix is to add an official non-null unique key to the focalboard_file_info table.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-52815.

**Comment by amyblais** [comment]
Notes from a developer on the ticket:

This issue seemed to have been related to product behavior more so than the fact that it was running in k8s. In particular, this fix seems to indicate it was related to focalboard expectations:

```
USE mattermost;
ALTER TABLE focalboard_file_info ADD COLUMN mysql_fix INT NOT NULL INVISIBLE AUTO_INCREMENT UNIQUE KEY;
```

Focalboard has recently been moved to be community maintained. @cerebrate Is the issue still present on your end?

**Comment by cerebrate** [comment]
Sorry for the delay in getting back to you.

The issue isn't still present on my end because, well, I applied that workaround and it was a one-time fix. :) I haven't set up a second Mattermost install using a mysql-operator back-end since then (I believe MySQL is deprecated now?), so I haven't experienced any recurrence of it myself.

I would agree that it's not a k8s-specific issue; it's a MySQL-installed-as-high-availability issue (which is the default even for a single-node deployment using mysql-operator, which is where k8s comes in), because one particular Focalboard-created table isn't compatible with HA-mode MySQL.

Go isn't one of my languages, alas, but as far as I can tell from a perusal of the mattermost/focalboard repository, the issue still exists in their data model. Maybe the best place to go from here, since Focalboard is now community-maintained, is to move this issue over to that repository?

**Comment by amyblais** [comment]
Sounds good, feel free to open a new issue in the focalboard repository 👍
