### ISSUE TITLE
Error during developer machine setup

### ISSUE THREAD

**Issue by fraziern** [mattermost/mattermost-server#7597]
#### Summary
When setting up local repos for development, an incomplete version of mattermost-redux is installed, resulting in webapp crashes.

#### Steps to reproduce
Cloned mattermost-webapp and mattermost-server. In mattermost-server, ran `make run`. Navigated to localhost:8065. Webapp goes through user account creation, and channel creation, then hangs.

#### Observed behavior (that appears unintentional) 
During `make run` an error is thrown from webpack, that begins:
```
ERROR in ./actions/job_actions.jsx
Module not found: Error: Can't resolve 'mattermost-redux/actions/jobs' in '/Users/nick/go/src/github.com/mattermost/mattermost-webapp/actions'
resolve 'mattermost-redux/actions/jobs' in '/Users/nick/go/src/github.com/mattermost/mattermost-webapp/actions'
  Parsed request is a module
```
I attempted a manual install of mattermost-redux in mattermost-webapp, and got an error that babel wasn't installed. 

I installed babel-cli, then tried again, and got errors that 3 other packages were not installed:
* babel-plugin-module resolver
* babel-preset-es2015
* babel-preset-stage-0

Installed these, then mattermost-redux installed, and webapp works.

#### Possible fixes
Possibly a versioning issue with the mattermost-redux package.json file?

**Comment by enahum** [comment]
Very strange as the dependencies you mention are listed in the `package.json` under dev-dependencies, probably you had an issue while installing the dependencies? `mattermost-redux` should build when running the post install script.

A few questions:
* What version of node do you have running?
* What version of yarn?
* Have you tried running `make nuke` or `make clean` in the server folder or `make clean` in the webapp folder before trying again?

**Comment by lindy65** [comment]
Hi @fraziern,

Circling back on this to see whether your issue is resolved?

**Comment by fraziern** [comment]
* node 8.0.0
* yarn 0.27.5
* Tried `make clean` in the webapp folder and all the errors are back

Now when I try to manually install I'm getting new errors...

```
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated remote-redux-devtools-on-debugger@0.8.2: The package have been renamed to `remotedev-rn-debugger`, we will stop publish the old name on next major version.
npm WARN gentlyRm not removing /Users/nick/go/src/github.com/mattermost/mattermost-webapp/node_modules/socketcluster-server/node_modules/.bin/uuid as it wasn't installed by /Users/nick/go/src/github.com/mattermost/mattermost-webapp/node_modules/socketcluster-server/node_modules/uuid
npm WARN gentlyRm not removing /Users/nick/go/src/github.com/mattermost/mattermost-webapp/node_modules/.bin/jest as it wasn't installed by /Users/nick/go/src/github.com/mattermost/mattermost-webapp/node_modules/jest
npm WARN gentlyRm not removing /Users/nick/go/src/github.com/mattermost/mattermost-webapp/node_modules/espree/node_modules/.bin/acorn as it wasn't installed by /Users/nick/go/src/github.com/mattermost/mattermost-webapp/node_modules/espree/node_modules/acorn
npm WARN gentlyRm not removing /Users/nick/go/src/github.com/mattermost/mattermost-webapp/node_modules/.bin/uglifyjs as it wasn't installed by /Users/nick/go/src/github.com/mattermost/mattermost-webapp/node_modules/uglify-js
npm WARN gentlyRm not removing /Users/nick/go/src/github.com/mattermost/mattermost-webapp/node_modules/.bin/semver as it wasn't installed by /Users/nick/go/src/github.com/mattermost/mattermost-webapp/node_modules/semver
npm WARN gentlyRm not removing /Users/nick/go/src/github.com/mattermost/mattermost-webapp/node_modules/.bin/nopt as it wasn't installed by /Users/nick/go/src/github.com/mattermost/mattermost-webapp/node_modules/nopt
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> node-sass@4.5.3 install /Users/nick/go/src/github.com/mattermost/mattermost-webapp/node_modules/node-sass
> node scripts/install.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'fast-deep-equal'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/nick/go/src/github.com/mattermost/mattermost-webapp/node_modules/har-validator/node_modules/ajv/lib/compile/resolve.js:4:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm WARN react-addons-test-utils@15.6.2 requires a peer of react-dom@^15.4.2 but none was installed.
npm WARN redux-offline@1.1.5 requires a peer of redux@>=3 but none was installed.
npm WARN The package enzyme-adapter-react-15 is included as both a dev and production dependency.
npm WARN The package react-test-renderer is included as both a dev and production dependency.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.5.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by lindy65** [comment]
Thanks @fraziern,

I'll ask one of our devs if they can help you troubleshoot further.

**Comment by fraziern** [comment]
OK well I tried a `make nuke` and then a reinstall and now it seems to be working. 😳

**Comment by lindy65** [comment]
Good news!  Thanks @fraziern :)

I'll close this issue off as resolved then...

**Comment by tejasbubane** [comment]
Came across same error today. This is what is required: https://github.com/mattermost/mattermost-webapp/blob/master/Makefile#L20

**Comment by lindy65** [comment]
Thanks for posting this back to the issue @tejasbubane 👍
