### ISSUE TITLE
API used to delete a team break Mattermost UI

### ISSUE THREAD

**Issue by devnied** [mattermost/mattermost-server#8025]
#### Summary
When we used the API to delete a Team /api/v4/teams/{team_id} the mattermost UI display a blank screen for all pages (admin also)

#### Steps to reproduce
1. Create a new team with the UI
1. Delete this team with the API
1. Refresh the UI
1. The UI display a blank screen with some javascript error.

Tested with Mattermost 4.4.5

#### Expected behavior
The Matermost UI must display all the user's teams without the deleted one.

#### Observed behavior (that appears unintentional) 
A blank screen with a javascript error:
```
Uncaught (in promise) TypeError: Cannot read property 'localeCompare' of undefined
    at r (https://mattermost.xxxxx.com/static/main.db580b8946c8efe65bb4.js:1:1659940)
    at Array.sort (native)
    at a.value (https://mattermost.xxxxx.com/static/1.851e45b3078de7868ecd.js:1:2747)
    at d._renderValidatedComponentWithoutOwnerOrContext (https://mattermost.xxxxx.com/static/main.db580b8946c8efe65bb4.js:1:1861844)
    at d._renderValidatedComponent (https://mattermost.xxxxx.com/static/main.db580b8946c8efe65bb4.js:1:1861971)
    at d.performInitialMount (https://mattermost.xxxxx.com/static/main.db580b8946c8efe65bb4.js:1:1857812)
    at d.mountComponent (https://mattermost.xxxxx.com/static/main.db580b8946c8efe65bb4.js:1:1856858)
    at Object.mountComponent (https://mattermost.xxxxx.com/static/main.db580b8946c8efe65bb4.js:1:572617)
    at d.performInitialMount (https://mattermost.xxxxx.com/static/main.db580b8946c8efe65bb4.js:1:1857972)
    at d.mountComponent (https://mattermost.xxxxx.com/static/main.db580b8946c8efe65bb4.js:1:1856858)
```

#### Possible fixes
This issue is releated to the endpoint `/api/v4/users/me/teams/members`, this endpoint must not return the deleted teams for the current user.

**Comment by lindy65** [comment]
Hi @devnied,

Thanks for your report,

We have reproduced your issue and have filed [this ticket](https://mattermost.atlassian.net/browse/PLT-8494) to address it.

**Comment by lindy65** [comment]
I'll close this issue off for now and we can track via the ticket linked above.
