### ISSUE TITLE
mattermost-server failed to start

### ISSUE THREAD

**Issue by electronix001** [mattermost/mattermost-server#8135]
Hello
How can i solve this problem :

[2018/01/22 12:21:00 CET] [INFO] Systemübersetzungen geladen für 'de' von '/opt/mattermost/i18n/de.json'
[2018/01/22 12:21:00 CET] [INFO] Aktuelle Version ist 4.2.0 (4.2.0/Wed Sep 13 22:25:30 UTC 2017/a5ce36d0882ae1b4b409a7b68233bf89591a5f95/38697f6cf2a9183e410e88acd13191390711d38f)
[2018/01/22 12:21:00 CET] [INFO] Enterprise aktiviert: true
[2018/01/22 12:21:00 CET] [INFO] Aktuelles Arbeitsverzeichnis ist /opt/mattermost/bin
[2018/01/22 12:21:00 CET] [INFO] Konfigurationsdatei geladen von /opt/mattermost/config/config.json
[2018/01/22 12:21:00 CET] [INFO] Able to write files to local storage.
[2018/01/22 12:21:00 CET] [INFO] Server wird initialisiert...
[2018/01/22 12:21:00 CET] [INFO] Pinging SQL master database
[2018/01/22 12:21:01 CET] [INFO] Initializing job API routes
[2018/01/22 12:21:01 CET] [INFO] Initializing plugin: jira
[2018/01/22 12:21:01 CET] [INFO] Initializing plugin: ldapextras
[2018/01/22 12:21:01 CET] [INFO] Starte 4 Websocket-Hubs
[2018/01/22 12:21:01 CET] [INFO] Lizenzschlüssel von https://mattermost.com benötigt um Enterprise Features freizuschalten.
[2018/01/22 12:21:01 CET] [INFO] Starte Server...
[2018/01/22 12:21:01 CET] [INFO] Server hört auf :443
[2018/01/22 12:21:01 CET] [INFO] Starting workers
[2018/01/22 12:21:01 CET] [INFO] Starting schedulers
2018/01/22 12:21:04 [INFO] acme: Registering account for
2018/01/22 12:21:05 [INFO][chat.mount-soft.eu] acme: Obtaining bundled SAN certificate
2018/01/22 12:21:05 [INFO] acme: Registering account for
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc8 pc=0xc3df02]

goroutine 2267 [running]:
github.com/mattermost/platform/vendor/github.com/rsc/letsencrypt/vendor/github.com/xenolf/lego/acme.(*Client).getChallenges.func1(0xc42236d2d0, 0xc4229ad1a0, 0xc4229ad140, 0xc4219d7c40, 0x19)
        /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/vendor/github.com/rsc/letsencrypt/vendor/github.com/xenolf/lego/acme/client.go:550 +0x132
created by github.com/mattermost/platform/vendor/github.com/rsc/letsencrypt/vendor/github.com/xenolf/lego/acme.(*Client).getChallenges
        /var/lib/jenkins/jobs/msr/jobs/d/jobs/enterprise-release/workspace/src/github.com/mattermost/platform/vendor/github.com/rsc/letsencrypt/vendor/github.com/xenolf/lego/acme/client.go:564 +0x149

**Comment by SmartHoneybee** [comment]
> `Aktuelle Version ist 4.2.0 (4.2.0/Wed Sep 13 22:25:30 UTC 2017/a5ce36d0882ae1b4b409a7b68233bf89591a5f95/38697f6cf2a9183e410e88acd13191390711d38f)
`

Could you try to upgrade to a more recent version (e.g. 4.6.0)?

> ```
> acme: Registering account for
> ```

Double check your *Let's Encrypt* settings.

**Comment by lindy65** [comment]
There was an issue with Lets Encrypt being broken on Mattermost servers but a fix has been submitted - https://mattermost.atlassian.net/browse/ABC-198

**Comment by lindy65** [comment]
I'll close this issue off for now and if it reproduces after v4.7 is released on Feb 16th, feel free to reopen.
