### ISSUE TITLE
Cannot build mattermost-webapp from v4.10.0 tag

### ISSUE THREAD

**Issue by ryantm** [mattermost/mattermost-server#8806]
#### Summary
`make build` in mattermost-webapp v4.10.0 tag has error with mattermost-redux

#### Steps to reproduce

```
git clone git@github.com:mattermost/mattermost-webapp
git checkout -b v4.10.0 v4.10.0
make build
```

#### Expected behavior
`make build` succeeds

#### Observed behavior (that appears unintentional) 

```
> mattermost-redux@1.2.0 build /home/ryantm/p/mattermost-webapp/node_modules/mattermost-redux
> babel src --out-dir .

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/ryantm/p/mattermost-webapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:178:20
    at Array.map (native)
    at Function.normalisePlugins (/home/ryantm/p/mattermost-webapp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)

npm ERR! Linux 4.4.0-121-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v4.9.1
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! mattermost-redux@1.2.0 build: `babel src --out-dir .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mattermost-redux@1.2.0 build script 'babel src --out-dir .'.
npm ERR! This is most likely a problem with the mattermost-redux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel src --out-dir .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mattermost-redux
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls mattermost-redux
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ryantm/p/mattermost-webapp/node_modules/mattermost-redux/npm-debug.log
Makefile:17: recipe for target '.npminstall' failed
make: *** [.npminstall] Error 1
```

#### Possible fixes

* I noticed there is a newer version of mattermost-redux released on GitHub.

#### System details
```
$ uname -a
Linux ryantm-1604.pololu.internal 4.4.0-121-generic #145-Ubuntu SMP Fri Apr 13 13:47:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
```

**Comment by amyblais** [comment]
Hi @ryantm,

Apologies for the delay - just giving you a quick update here that I have let our engineers know about the questions you posted above, hoping to get feedback from our engineers soon.

**Comment by AndersonWebStudio** [comment]
Hi @ryantm , My test was using NPM version 5.6.0, are you able to upgrade?

**Comment by ryantm** [comment]
It looks like that worked, thank you!
