### ISSUE TITLE
Sigsegv when shutting down, after creating team from cli

### ISSUE THREAD

**Issue by fbartels** [mattermost/mattermost-server#9393]
#### Summary
The mattermost binary throws a sigsev and gives a non zero exit code when creating a channel.

#### Steps to reproduce
execute `mattermost channel create --team univention --name matterbridge1 --display_name 'Matterbridge Demo Channel'` 

```
Version: 5.2.0
Build Number: 5.2.1
Build Date: Thu Aug 23 17:03:59 UTC 2018
Build Hash: d2945cdd77bdf1ee03367a0d45624094fb936c19
Build Enterprise Ready: true
DB Version: 5.2.0
```
Mattermost is running in an Ubuntu 16.04 Docker container.

Rerunning the command will give a duplicate keys message, since the channel has been successfully created and Mattermost only threw the error when shutting down.

#### Expected behavior
Exit code zero and no sigsev

#### Observed behavior (that appears unintentional) 
In my Docker image I can repeatedly trigger the below error message with Mattermost 5.2.1 (I have not tried 5.2.0, with 5.1.0 execution was still ok):

```
mattermost channel create --team univention --name matterbridge1 --display_name 'Matterbridge Demo Channel'
{"level":"info","ts":1536592016.3524618,"caller":"utils/i18n.go:83","msg":"Loaded system translations for 'en' from '/opt/mattermost/i18n/en.json'"}
{"level":"info","ts":1536592016.3526921,"caller":"app/app.go:195","msg":"Server is initializing..."}
{"level":"info","ts":1536592016.3561463,"caller":"sqlstore/supplier.go:200","msg":"Pinging SQL master database"}
{"level":"info","ts":1536592016.446978,"caller":"app/license.go:44","msg":"License key from https://mattermost.com required to unlock enterprise features."}
{"level":"info","ts":1536592016.4470954,"caller":"app/plugin.go:100","msg":"Starting up plugins"}
{"level":"info","ts":1536592016.4513488,"caller":"app/app.go:264","msg":"Stopping Server..."}
{"level":"info","ts":1536592016.4514897,"caller":"app/web_hub.go:120","msg":"stopping websocket hub connections"}
{"level":"warn","ts":1536592016.451586,"caller":"app/web_hub.go:125","msg":"We appear to have already sent the stop checking for deadlocks command"}
{"level":"info","ts":1536592016.4516222,"caller":"app/plugin.go:156","msg":"Shutting down plugins"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb3e3f2]

goroutine 2283 [running]:
github.com/mattermost/mattermost-server/plugin.(*Environment).RunMultiPluginHook(0x0, 0xc4219bff80, 0xd)
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/plugin/environment.go:273 +0x42
github.com/mattermost/mattermost-server/app.(*App).CreateChannel.func1()
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/app/channel.go:206 +0x84
github.com/mattermost/mattermost-server/app.(*App).Go.func1(0xc421981320, 0xc4200d6580)
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/app/app.go:483 +0x27
created by github.com/mattermost/mattermost-server/app.(*App).Go
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/app/app.go:482 +0x52
````

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by fbartels** [comment]
I have just now also tried it on a different machine and have disabled the plugins before trying to create my channel. Still the error persists:

````
$ ./mattermost channel create --team univention --name matterbridge2 --display_name 'Matterbridge Demo Channel'
{"level":"info","msg":"Stopping Server..."}
{"level":"info","msg":"stopping websocket hub connections"}
{"level":"warn","msg":"We appear to have already sent the stop checking for deadlocks command"}
{"level":"info","msg":"Server stopped"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xecd4ca]

goroutine 1 [running]:
github.com/mattermost/mattermost-server/app.(*App).Config(...)
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/app/config.go:27
github.com/mattermost/mattermost-server/cmd/mattermost/commands.InitDBCommandContextCobra(0x1c03380, 0x9, 0xc42013e880, 0xc4200accd0)
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/init.go:20 +0xea
github.com/mattermost/mattermost-server/cmd/mattermost/commands.createChannelCmdF(0x1c03380, 0xc42013b140, 0x0, 0x6, 0x0, 0x0)
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/channel.go:145 +0x4b
github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).execute(0x1c03380, 0xc42013aea0, 0x6, 0x6, 0x1c03380, 0xc42013aea0)
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:762 +0x468
github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1bff360, 0x11161e0, 0xc4202b1f01, 0x1c4e3f0)
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra.(*Command).Execute(0x1bff360, 0xc42008c058, 0x0)
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/mattermost/mattermost-server/cmd/mattermost/commands.Run(0xc4200b0010, 0x8, 0x8, 0xc420075f78, 0xc42008c058)
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/cmd/mattermost/commands/root.go:14 +0x6d
main.main()
        /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/cmd/mattermost/main.go:30 +0x63
```

**Comment by fbartels** [comment]
fyi error does not appear with the 5.3 rc:
```
$ ./mattermost -c /etc/mattermost/config.json version
{"level":"info","ts":1536652120.9674816,"caller":"utils/i18n.go:83","msg":"Loaded system translations for 'en' from '/opt/mattermost/i18n/en.json'"}
{"level":"info","ts":1536652120.967543,"caller":"app/app.go:195","msg":"Server is initializing..."}
{"level":"debug","ts":1536652120.96865,"caller":"utils/html.go:30","msg":"Parsing server templates at /opt/mattermost/templates"}
{"level":"info","ts":1536652120.9811943,"caller":"sqlstore/supplier.go:200","msg":"Pinging SQL master database"}
{"level":"debug","ts":1536652121.0151072,"caller":"sqlstore/preference_store.go:41","msg":"Deleting any unused pre-release features"}
{"level":"debug","ts":1536652121.01752,"caller":"jobs/schedulers.go:29","msg":"Initialising schedulers."}
{"level":"debug","ts":1536652121.0179179,"caller":"jobs/schedulers.go:29","msg":"Initialising schedulers."}
{"level":"debug","ts":1536652121.0183005,"caller":"utils/license.go:83","msg":"We could not find the license key in the database or on disk at /opt/mattermost/config/mattermost.mattermost-license"}
{"level":"info","ts":1536652121.0186918,"caller":"app/license.go:44","msg":"License key from https://mattermost.com required to unlock enterprise features."}
Version: 5.3.0
Build Number: 5.3.0-rc1
Build Date: Tue Sep  4 17:54:10 UTC 2018
Build Hash: d2190527eafdae31e14ba0832dcfb79a0a1e223b
Build Enterprise Ready: true
DB Version: 5.3.0
```

**Comment by amyblais** [comment]
Hi @fbartels, thank you for reporting this.

Does it look like this is not an issue on v5.3?

**Comment by fbartels** [comment]
Yes, it appears so. Since the 5.3 release is around the corner I think I'm going to skip 5.2, then.
