### ISSUE TITLE
Server crash on inaccessible zoom.us server

### ISSUE THREAD

**Issue by vpecinka** [mattermost/mattermost-server#9810]
#### Summary
When mattermost server cannot access internet directly, an attempt to connect to the zoom.us server (from the zoom plugin) crashes the server.

#### Steps to reproduce

Having Mattermost 5.4.0 with Zoom plugin enabled and running. Use default endpoints, setup key, secret and token.

1. Deploy mattermost on a server without direct access to the internet, no http/https proxy usage
2. Click on the camera icon in the channel
3. Server crashes
4. Enable access to the internet from the server (e.g. allow NAT of disable outgoing firewall)
5. Click on camera icon - server works

#### Expected behavior
We have an paid account in Zoom and tried to integrate Zoom with Mattermost. We deploy Mattermost server in out Kubernetes cluster. There are nodes with no direct access to the internet (this is by default), and those which I can select and have NAT support.

When deployed Mattermost on the nodes without NAT, the server crashes completely (POD is restarted). When deployed on the nodes with NAT support, server keeps going. 

#### Observed behavior (that appears unintentional) 
On the user side there is only this message:
```
We could not verify your Mattermost account in Zoom. Please ensure that your Mattermost email address matches your Zoom email address.
```

However, what I can see in the log is the following:

```
panic: invalid WriteHeader code 0

goroutine 2585818 [running]:
net/http.checkWriteHeaderCode(0x0)
    /usr/local/go/src/net/http/server.go:1092 +0xe9
net/http.(*response).WriteHeader(0xc008f58c40, 0x0)
    /usr/local/go/src/net/http/server.go:1105 +0x63
github.com/mattermost/mattermost-server/plugin.(*httpResponseWriterRPCServer).WriteHeader(0xc006fc5a70, 0x0, 0x2580d60, 0x0, 0x0)
    /home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/plugin/http.go:27 +0x3d
reflect.Value.call(0xc00befca80, 0xc003448df0, 0x13, 0x15678b0, 0x4, 0xc007db8f18, 0x3, 0x3, 0xc007222100, 0xc00e412130, ...)
    /usr/local/go/src/reflect/value.go:447 +0x449
reflect.Value.Call(0xc00befca80, 0xc003448df0, 0x13, 0xc000158f18, 0x3, 0x3, 0xc007edaab0, 0x186e920, 0xc000030370)
    /usr/local/go/src/reflect/value.go:308 +0xa4
net/rpc.(*service).call(0xc00dce8840, 0xc0092d6280, 0xc00b08f318, 0xc00b08f340, 0xc005dd1780, 0xc00a097840, 0x1312500, 0xc006e1b2b0, 0x182, 0x12ea040, ...)
    /usr/local/go/src/net/rpc/server.go:384 +0x14e
created by net/rpc.(*Server).ServeCodec
    /usr/local/go/src/net/rpc/server.go:481 +0x47e
```

**Comment by amyblais** [comment]
Hi @vpecinka,

What happens (in the UI) when the server crashes on step 3?

**Comment by vpecinka** [comment]
Hi @amyblais , just simple message
```
We could not verify your Mattermost account in Zoom. Please ensure that your Mattermost email address matches your Zoom email address.
```
 I gues this message is from the frontend, as server crashes and cannot produce anything more :-)

**Comment by hanzei** [comment]
Hey @vpecinka,

I think I found and fixed the bug. Can you please try to reproduce the error with 
[com.mattermost.zoom-1.0.2.tar.gz](https://github.com/mattermost/mattermost-server/files/2561237/com.mattermost.zoom-1.0.2.tar.gz)?

**Comment by vpecinka** [comment]
Hi @hanzei 

I confirm, that this release you provided doesn't crash the server! Thank you.
